### ISSUE TITLE
git v4432 tag corresponds to svn r4437

### ISSUE THREAD

**Issue by jbeich** [DCurrent/openbor#1]
r4433 (aka a91df8ba04bd) bumped `MAX_BTN_NUM` which may affect old saves. Can you move the tag to real r4432 (aka ba1eb4f62cec)?

**Comment by DCurrent** [comment]
_Can you move the tag to real r4432 (aka ba1eb4f)?_ - Not sure what you mean by that.

**Comment by DCurrent** [comment]
I think we've got the tags fixed now. Closing ticket.
