### ISSUE TITLE
Bombs can't fall in holes

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#10]
BloodBane helped me to find another bug: Entities thrown like BOMB can't fall in holes.

As he had explained:
I've tried it myself and did reproduce this bug
I also tried using other build to reproduce that bug but it didn't happen
So that means the cause is OpenBoR build. 

- The not buggy one is **OpenBoR v3.0 Build , Compile Date: Nov  8 2016**
- while the buggy one is **OpenBoR v3.0 Build , Compile Date: Dec 22 2016 - OpenBOR_v3.0_Build_4419**

 Looks like some change in the engine caused this bug.

The bug is still present in builds **4432** (Compile Date: 2017-01-25) and **4453** (Compile Date: Apr  8 2017)

**Comment by DCurrent** [comment]
I'll need some help with this one. Please try to find the specific version. I need the release number - compile date doesn't really help that much. Then I can compare the code and trace bug. Thanks!

**Comment by dbaldan** [comment]
I need to make more tests, but it seems to be working in 3994.

Talking about the builds, I don't remember when this started, but I remember we could get the build version in the log file, but then after a version 3, no more builds have the build version in the log files, and this is very helpful for cases like this.

**Comment by dbaldan** [comment]
@whitedragon0000 I've tried this in your latest release...and the bug is still there.

**Comment by whitedragon0000** [comment]
fixed!!

**Comment by dbaldan** [comment]
@whitedragon0000 Can you compile with this fix, please?

**Comment by dbaldan** [comment]
@whitedragon0000 I've tested it. Works sometimes, but sometimes not.
For example, when it works, if the entity has any antiwall code, it will trigger inside the hole.

See the arrow. Even with the same attributes of other bombs, it won't fall on the hole:
subject_to_wall   1
subject_to_platform 1
subject_to_hole 1
no_adjust_base 0

![avengers - 0037](https://user-images.githubusercontent.com/31666009/34369583-fb1327c0-eaa3-11e7-83e5-1d6bacf94a27.png)
