### ISSUE TITLE
Facing 1

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#102]
If you create text or an object facing proper direction, the engine default flips images so you then are to use facing 1 to turn it back the way it was intended.

There is a issue with facing 1 it will actually not be facing the right way upon spawn for the first frame. 

can see this issue if entity is at start of a level and there is a story cutscene for example.

so current workaround is you need to physically flip the images in image editor (photoshop or paint etc) and not use facing command at all and it will then flip automatically in engine.... or have a blank image with delay 1 so that the engine bug wont be noticeable.

maybe this is the way its all meant to be done but unsure if the delay in facing is known so thought I would report it just in case

**Comment by DCurrent** [comment]
The engine is intentionally designed to skip updating fresh entities - which does mean some things do not take effect until the second frame. I can look at changing this later, but since it isn't really a bug I'm closing for now.

**Comment by nsw27** [comment]
I know you have closed this but I think its also linked to this same issue.

if you have a entity that is to be spawned but have a spawn01 etc script in first frame the entity wont appear at all.

example the drip spawn like this will cause bodexp to not appear at all

`name		bodexp
type		none
shadow	0

palette none

animationscript data/scripts/script.c

anim	idle
	loop	0
	bbox	0 0 0 0
delay 30
sound   data/sounds/mdead3.wav
@cmd    spawn01 "drip" 0 0 1
	offset	238 256
	frame	data/chars/misc/bod/1.png
	delay	10
	frame	data/chars/misc/bod/2.png
	frame	data/chars/misc/bod/3.png
	frame	data/chars/misc/bod/4.png
	frame	data/chars/misc/bod/5.png
	frame	data/chars/misc/bod/6.png
	delay	3
	frame	data/chars/misc/bod/7.png
	frame	data/chars/misc/bod/8.png
	frame	data/chars/misc/bod/9.png
	frame	data/chars/misc/bod/10.png
	frame	data/chars/misc/bod/11.png
	frame	data/chars/misc/bod/12.png
	frame	data/chars/misc/bod/13.png
	frame	data/chars/misc/bod/14.png
@cmd    spawn01 "bloodfl" 30 20 -10
	frame	data/chars/misc/bod/15.png
	frame	data/chars/misc/bod/16.png
	frame	data/chars/misc/bod/17.png
	frame	data/chars/misc/bod/18.png
	fshadow	0
	frame	data/chars/misc/bod/19.png`

buy using delay 1 and having another first frame before spawning it will work.


`name		bodexp
type		none
shadow	0

palette none

animationscript data/scripts/script.c

anim	idle
	loop	0
	bbox	0 0 0 0
delay 1
sound   data/sounds/mdead3.wav
offset	238 256
	frame	data/chars/misc/bod/1.png
	delay	29
@cmd    spawn01 "drip" 0 0 1
	offset	238 256
	frame	data/chars/misc/bod/1.png
	delay	10
	frame	data/chars/misc/bod/2.png
	frame	data/chars/misc/bod/3.png
	frame	data/chars/misc/bod/4.png
	frame	data/chars/misc/bod/5.png
	frame	data/chars/misc/bod/6.png
	delay	3
	frame	data/chars/misc/bod/7.png
	frame	data/chars/misc/bod/8.png
	frame	data/chars/misc/bod/9.png
	frame	data/chars/misc/bod/10.png
	frame	data/chars/misc/bod/11.png
	frame	data/chars/misc/bod/12.png
	frame	data/chars/misc/bod/13.png
	frame	data/chars/misc/bod/14.png
@cmd    spawn01 "bloodfl" 30 20 -10
	frame	data/chars/misc/bod/15.png
	frame	data/chars/misc/bod/16.png
	frame	data/chars/misc/bod/17.png
	frame	data/chars/misc/bod/18.png
	fshadow	0
	frame	data/chars/misc/bod/19.png`

**Comment by DCurrent** [comment]
Yes, these are exactly the same - and again, not really a bug, and not really anything I can change without causing tons of problems elsewhere. If you need an action to take place immediately on spawn, then use an _onspawnscript_.
