### ISSUE TITLE
positioning of entities sequence in models text

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#103]
Unsure if this is intentional or known but the positioning/order of known and load entities on models text affects the engine.

http://www.chronocrash.com/forum/index.php?topic=3841.msg52890#msg52890

Example if you have a item spawned into level directly then it will work. but  if you have a enemy who drops an item in a level it is wont work depending on where that item is located in models.txt file (after players ,enemies and flashes always works) 

Its a odd quirk and obviously wont be high on a radar but thought its worth reporting again as the issue may be ingrained and affect other things also.

**Comment by DCurrent** [comment]
@nsw27 Please provide some details and text examples of this. Your report and linked post contradict each other. Linked post says items spawn but won't drop from parent entity, report says items drop from parent entity but won't spawn.
