### ISSUE TITLE
Palette None

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#11]
Since version **OpenBOR_v3.0_Build_4469 (which is identified as 4569)** entities with "palette none" will make the engine closes itself, giving this error log:

> Fatal Error in load_cached_model, file: data/chars/misc/sflash.txt, line 7, message: Palette failed to load color table from image!

It's a version bug or something had changed? Because versions until **OpenBOR_4453** works fine.

**Comment by DCurrent** [comment]
It's a known issue and there is a fix on the way. Just a oversight on my part while upgrading the palette loading code.
