### ISSUE TITLE
LoadGame vs globalVariable

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#111]
## Description
On Android, I've discovered that if you have a globalvariable active while you load a game, it will make the engine crash. It will close like it was a NULL POINTER, with no trace on the log.

This error happens only on Android port. On Windows, it works normally.

### Reproduce
It can be a little tedius to reproduce the error and I can provide an easier version to reproduce it.

- Download my game here https://gamejolt.com/games/avengers-united-battle-force/14591
- Use the provided Android build (4432), either on your phone or using an emulator like Nox Player (I tested in both cases)
- Go to story mode, get the Avengers Icon (which sets an global variable "HelperControl") but do not use it.
- Continue the game normally, beating Hydra Golem. The globalvariable will be still on (you can confirm by the blinking AV logo in red)
- Next, you will be on the branch screen, just moves foward (althought both rotes have the same issue)
- **QUIT THE GAME** and choose LOAD GAME. You will be on the same stage again. **ITS IMPORTANT TO QUIT AND LOAD THE GAME BEFORE THE NEXT SCREEN**
- Beat the next stage, killing Viper. You can use the AV item if you want, since you will get another, but its important to keep it when you finish the stage
- Next you will be the Bonus Stage. Just beat it
- Now you are on the Truck stage. Once you beat the stage, you would see a SCENE (unlock2.txt) normally, but instead you will see a crash.

The issue will happen only if you had quit and loaded the game. If you go ahead without loading a game, nothing wrong will happen.

This error happens only before the stages where I set a global variable, so I can unlock characters. On all other stages, nothing happens. You can choose the upper branch and it will happens right after the bonus stage.

### Debug
There are two globalVariables in course here and, as far as I know, globalVar are stored on savedgames.

"HelperControl"
Gets activated when you get the item AVITEM, which has a didhitscript to activate the variable
```
void main()
{
   setglobalvar("HelperControl", 1);
}
```
"clearCount"
Used to track how many unlocked characters you have. I set it manually on a spawn during the level "hydra-2.txt"

```
spawn   empty
@script
void main()
{
    setglobalvar("clearCount", 2);
}
@end_script
coords   180 189
at   0

```

### Expected behavior
The load game should work.

### Version
- Android
- 4432 (ok), 6330 and beyond (bug).

## Additional context
I will add more information once I can. I've spent some days trying to figure it until I noticed that this happens only on 6315 and beyond on Android. I will try to track down exactly which version breaks this.
@DCurrent this is the bug I've talked about

**Comment by DCurrent** [comment]
@dbaldan thank you. if you can find the build or better yet, the code commit (assuming you can compile), that should get us very close to the solve point.

**Comment by dbaldan** [comment]
@DCurrent the last bug fix made my @msmalik681  (about the logo.gif) seams to be solved this issue, as my initial tests are telling me.

I will further investigate it to confirm this.

@msmalik681 did you made that fix based on the last engine version?

**Comment by msmalik681** [comment]
@dbaldan The test build was based on v6412.  If that version has fixed this issue please close this issue down.

**Comment by dbaldan** [comment]
@msmalik681 Thanks.
As I've explained above, I will close this once I am sure this is not happening anymore.

**Comment by DCurrent** [comment]
Issue resolved for original reporter. I've tested in a sterile module and found global var persistence is working. Closing ticket.
