### ISSUE TITLE
Legacy Blast Enables Friendly Fire

### ISSUE THREAD

**Issue by DCurrent** [DCurrent/openbor#124]
## Description
Attack boxes may optionally cause an entity to bowl over its allies as it flies through the air. This is accomplished by an attack box on the entity's falling animation, and the that knocked entity down applying a ["blasted" state](http://www.chronocrash.com/apps/wiki/obor/index.php?title=Entity_Property_(Scripting)#blast_state), allowing entity to cause friendly fire until landing.

However, the legacy Blast command applies the blasted state whether or not the target was knocked down. This can lead to a situation where an entity with knockdown resistance receives a blast attack and remains standing, but still has blasted state - thus enabling all of its attacks to hit allies.

See [here for original report](http://www.chronocrash.com/forum/index.php?topic=3482.msg48043#msg48043).

### Reproduce
Provide step by step instructions to reproduce the behavior. Include any text files, scripts, etc., along with the engine log. In some cases, we may need a download link to your entire module:
1. Make sure friendly fire is disabled in the module
2. Create entity with attack boxes in fall as normal. 
3. Give entity sufficient knockdown resistance (nofall or knockdowncount).
4. Allow entity to receive a legacy blast attack.
5. Entity can now cause friendly fire with all of its normal attacks.

### Expected behavior
Entity should only hit with friendly fire when it is knocked down with a blasting effect, and cease after landing.

### Version
Unknown - caused by a conflict of blast feature and knockdown resistance. Likely an extremely old bug only discovered recently.

**Comment by dbaldan** [comment]
Sweet, really thanks!
