### ISSUE TITLE
Request to edit virtual keys.

### ISSUE THREAD

**Issue by stizzo1** [DCurrent/openbor#126]
I reported in this thread:

http://www.chronocrash.com/forum/index.php?topic=4313.0

**Comment by msmalik681** [comment]
@DCurrent correct me if I am wrong but this seems more like a request then a bug or engine fault should it be here ?

**Comment by DCurrent** [comment]
Requests can be here, but since this one is very low priority and on the back burner, I'd rather close it for now so the real issues take center stage.
