### ISSUE TITLE
Logo.gif doesn't shows in Android port

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#128]
## Description
Logo.gif works fine in Windows port, but in Android port, it doesn't shows.

### Reproduce
1. Get any game which uses logo.gif
2. Run it on Android

### Expected behavior
Logo.gif should appear.
I've tested it on my Avengers game, which uses logo.gif and logo.txt for animation.
The animation runs fine, but the logo.gif doesn't appears.

### Version

- Platform (windows and Android)
- Windows (works ok) - 6412. Android (doesn't works) 6412.

**Comment by DCurrent** [comment]
I don't have OpenBOR on Android so this is pretty much impossible for me to test and diagnose. @Plombo would you have an idea off the top of your head? If not guess I can poke around for something obvious in the code...

**Comment by Plombo** [comment]
I don't have anything off the top of my head, no.

**Comment by DCurrent** [comment]
@Plombo Thanks for chiming in. Oh well, guess I'll poke about. I know slightly less than 0 about the ports, but maybe it's just some silly oversight.

**Comment by dbaldan** [comment]
I think @msmalik681 can give a hand here.

**Comment by msmalik681** [comment]
I am switching to a new pc at the moment.  I will find a way to fix this as soon as I am back up and running again.

@DCurrent anyone with windows and a strong enough cpu can run bluestacks (android virtual machine) this is a great way to debug android apps.  I will make a tutorial on how to set this up.

**Comment by msmalik681** [comment]
My tests show that this is a issue with all builds including windows.

logo.gif is displayed if there is only 1 pak file and there is a direct load bypassing the pak selection menu.  When there are multiple mods in the pak folder any mod loaded from the pak selection menu it will miss the logo.gif file.

I have isolated the issue still trying to figure out how to fix it.

**Comment by msmalik681** [comment]
@dbaldan  can you try this test build both android and windows are there.  It worked for me so I think after pressing attack/start to pick a pak file from the menu the button press was still registered when the pak loaded and skipped the logo.gif.  Please report back with your results.

[](https://www.mediafire.com/file/zhid5h3g5570gwy/logo.gif.fix.test.zip/file)

**Comment by dbaldan** [comment]
@msmalik I tried to install this version, but it failed (Android 9.0)

**Comment by msmalik681** [comment]
Nsw25 also had a new security block try this:

https://support.mobile-tracker-free.com/hc/en-us/articles/360005346953-How-to-disable-Google-Play-Protect-

**Comment by dbaldan** [comment]
@msmalik681 I've followed that instruction and now it installs.
I've tried this test build and now the logo.gif is showing.

**Comment by msmalik681** [comment]
Good enough for me.  Thats is 3 people that have confirmed this issue resolved.

Closed.

**Comment by DCurrent** [comment]
Thanks @msmalik681.
