### ISSUE TITLE
Complete animationproperty

### ISSUE THREAD

**Issue by whitedragon0000** [DCurrent/openbor#13]
Need to complete animationproperty to get framecount and other props like:
enum _prop_summonframe_enum
enum _prop_starvelocity_enum
etc...

**Comment by DCurrent** [comment]
Just FYI, I have a week doing hurricane aid work, and will be taking this on (along with some other things) soon as I return ~2017-10-13.

**Comment by whitedragon0000** [comment]
Great!!

**Comment by DCurrent** [comment]
FYI for anyone monitoring this, I am starting back into the property project. Still a ways to go, but will be well worth it.

**Comment by DCurrent** [comment]
This isn't really an issue ticket, so I'm closing. the animation properties are mostly done, but are mixed with model properties that I''m still working on.
