### ISSUE TITLE
players can select same characters on select screen despite nosame 1

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#130]
## Description
if on select screen as player 1 and then player 2 enters select screen they can be hovering on same character. player 2 then presses start and can be that player and if player 1 hasn't moved they will still be on same player and can select the character also. despite having in level text

nosame 1

on further testing this also occurs if player 1 chooses character first.

if player who hasn't selected moves then they will go to next character and wont be able to select same character as intended.

### Expected behavior
once a player is selected it should be that any other player hovering on same character is then moved to the next available character to choose from and the selected character is no longer selectable for any other player

This was tested on PC versions.

**Comment by dbaldan** [comment]
@nsw27 please, always inform the build too.
I've tried to replicate it but it's working for me in build 6325

**Comment by nsw27** [comment]
its a shame openbor log doesn't detail the proper build number as it makes remembering build number difficult.

this is the build

[OpenBOR.zip](https://github.com/DCurrent/openbor/files/2998198/OpenBOR.zip)

if it cant be replicated on another mod perhaps its something in my game causing conflict ?

**Comment by nsw27** [comment]
update: this still occurs when I compile latest build.

**Comment by danielt3** [comment]
I confirmed that in build 7806 this bug does not happen anymore. Please, see attached package with an example and an exe of build 7806.

Even though not all versions log the build number indeed, there is the build date that can be really helpful to track the version.

[Issue_130.zip](https://github.com/DCurrent/openbor/files/4822777/Issue_130.zip)

**Comment by danielt3** [comment]
@DCurrent, could you please, review and close this issue?

**Comment by DCurrent** [comment]
Confirmed with test on original BOR with nosame enabled. Closing ticket.
