### ISSUE TITLE
Update requirements for linux build.

### ISSUE THREAD

**Issue by trislett** [DCurrent/openbor#137]
## Description

Not a bug. Just a request to add libvorbis-dev and libvpx-dev to the wiki as required libraries in the linux compiling instructions. Otherwise there will be errors with vorbis.h and vpx_decoder.h.

### Version

Xubuntu 18.04

Master- 02375fb
and
6412

**Comment by msmalik681** [comment]
Haxpor said he did compile on linux can you confirm these files are needed ?

If they are needed I will look into adding them.

**Comment by trislett** [comment]
Yes, it was required with a fresh install of ubuntu.

**Comment by msmalik681** [comment]
[Read this](https://wiki.hard-light.net/index.php/Fs2_open_on_Linux/Installing_the_Development_Libraries) I do not use linux but it seems like these are libraries you need to download.

@haxpor do you know why it will not compile on linux ?

**Comment by trislett** [comment]
@msmalik681 you are correct. These are libraries that need to be downloaded. Just to clarify, I have successfully compiled openbor. I am only suggesting to add a statement to the compiling instructions that these libraries may be necessary for future linux users.

e.g.,
Ubuntu
```
sudo apt install libsdl2-dev libsdl2-gfx-dev zlib1g-dev libpng16-dev libvorbis-dev libvpx-dev
git clone https://github.com/DCurrent/openbor.git
cd openbor/engine
./build.sh 4 amd64
```

**Comment by DCurrent** [comment]
Done! Thanks for the heads up.
