### ISSUE TITLE
"Remap" with strange results

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#14]
An user reported at my FB group that old mods with REMAP has strenge results, check the image bellow
Image: https://imgur.com/XFKfvqI
![error](https://user-images.githubusercontent.com/31666009/31050401-c3da8c62-a61f-11e7-9123-1194550b0ffa.jpg)

Build: Tested in OpenBor_v3.0_Build_4553 and OpenBOR_v3.0_Build_3849
Mod: Bare Knuckle 6 - Turn The Tide

**Comment by DCurrent** [comment]
@dbaldan The latest release is 4469 and contains several color table fixes. I'd suggest you test with it.

**Comment by dbaldan** [comment]
@DCurrent I think there is an inconsistency with the build numbers, take a look:

 21 Apr - 4469
 18 Apr - 4556

Version 4556 should be 4456 no? I suggest to rename that version, because its kinda confusing the way it is now.

**Comment by dbaldan** [comment]
Same result. Version 4469 is the one which doesn't support palette NONE.

**Comment by DCurrent** [comment]
I know the engine supports it, I put the fix in and tested it myself. Might not have been given a public release since then, I'll check on Tuesday when in in my office. In the meantime the version confusion was just a typo by whitedragon in the filename. It should be fixed now.

**Comment by dbaldan** [comment]
@DCurrent yeah, I think its not on the last public release.

About the version confusion, I think there is still something wrong, take a look:

v4432
v4453
v4455 
v4456 (Github calls it 4456 but the rar says 4556)
v4569

We had a jump between 4455 and 4569. Nothing too important, but may lead to confusion. I think you can rename the v4456 as v4556.

**Comment by DCurrent** [comment]
Sure, I'll take a look to make sure naming is matched up. Version jumps are perfectly normal though, because there may be a lot of code changes before we make a public release.

**Comment by DCurrent** [comment]
Versioning fixed - see #17. Check latest release for Palette NONE compatibility.
