### ISSUE TITLE
Backfall issue?

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#15]
This was reported at FB group:
_"I am doing some tests here and noticed that the enemies execute the animation BACKFALL normally, but the when the players reach frame with landframe, the animation get interrupted and go straight to animation RISE._

_Another detail is that when the player dies he performs the animation perfectly."_

Tested in builds **4419** and **4469**

**Comment by whitedragon0000** [comment]
check better this issue.
I checked the code and it's all right.
backfalls and normal falls are the SAME function, so if falls work well, also backfalls have to work well!
The rise function is called just ONE time, both for enemies and players.
I can't reach the problem.
The rise animation for players semms ok.
Try to set "risetime" for players

**Comment by dbaldan** [comment]
@whitedragon0000 the user had tested with setting risetime for player (using the double of the default value) and it works.

BUT...this is needed only when you set a BACKFALL. For the default FALL animation, its not needed to set a risetime. Which is strange.

**Comment by whitedragon0000** [comment]
tested and it works properly.
If you can, can you upload a video to show the difference between fall and backfall?

**Comment by dbaldan** [comment]
Thanks @whitedragon0000 . I've sugested to the user to interact with this issue himself, since I can't test this right now.
