### ISSUE TITLE
64-bit compatible executable build for Windows

### ISSUE THREAD

**Issue by haxpor** [DCurrent/openbor#156]
**Is your feature request related to a problem? Please describe.**
It seems the current build system will generate 32-bit version Windows build only, not 64-bit on system that has it. It's not a problem per se, but it'd be great to see OpenBOR would be able to generate optimized binary for system that has such support.

I didn't know whether there's a problem about generating 64-bit or not, thus the current build system doesn't take it into account. And I'm not sure Windows users rely on mingw to build OpenBOR or not, but just to notify there's 64-bit [mingw64](https://mingw-w64.org/) that might be able to help on this front.

**Describe the solution you'd like**
Able to build 64-bit version of Windows executable.

**Describe alternatives you've considered**
It will still run fine on both 32/64 bit system, so alternative course is no action taken until there would be gap of times dev could look into.

**Comment by Plombo** [comment]
We already support 64-bit builds for Linux, so 64-bit Windows builds wouldn't be hard to do. The only reason we've never had them is that there's just not much point to distributing two Windows binaries when our existing one runs without performance issues on both 32-bit and 64-bit systems.

**Comment by DCurrent** [comment]
Yeah sorry @haxpor, the numbers just don't support adding that extra complexity.

You could force load every single sprite from Street Fighter III into OpenBOR and you're still nowhere near one GB, never mind four.
