### ISSUE TITLE
unblockable attacks can now be blocked

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#163]
just compiled PC build again this morning and saw a new bug.

ALL unblockable attacks can now be blocked.... by either enemies or players wether directly linked to a player or an enemy or a projectile. 

so for example I have various bullets etc that are now blockable despite their settings

`name		gshotE
type		none
nolife		1 
#candamage	player npc obstacle
offscreenkill	20
palette		none
onspawnscript	data/scripts/faction1.c

anim	idle
	loop	1
	delay	2
	offset	7 7
	hitflash blood
	attack3	5 0 11 15 15 1 1 0 0 0
	frame	data/chars/misc/gshot3.png
	frame	data/chars/misc/gshot5.png
	frame	data/chars/misc/gshot3.png
	frame	data/chars/misc/gshot4.png`

I went back to one I compiled few days ago but still occurred back then also ( I just never noticed because I never let a enemy shoot me)

previous version of openbor I used which worked was

www.mediafire.com/file/n5fsbh5g85s779o/OpenBOR.zip/file

**Comment by dbaldan** [comment]
@nsw27 it's better to use the bug report template when reporting it

**Comment by nsw27** [comment]
has anyone investigated ? this affects all games not just mine so im surprised this wasn't picked up...

**Comment by nsw27** [comment]
any updates ?... no one has looked into yet ?

**Comment by dbaldan** [comment]
@nsw27 people are busy. Once someone take a look ai this, the will reply

**Comment by DCurrent** [comment]
I finally got a chance to dig in, and I can confirm the issue. I've recent done a lot of work on the blocking code, so this is obviously on me. Just need to find where I slipped up.
