### ISSUE TITLE
More than 18 paks causes crashing

### ISSUE THREAD

**Issue by Computerlabrat** [DCurrent/openbor#165]
If you have more than 18 paks in the paks folder, OpenBOR will crash as you scroll down past the last one in the window on the left. Having 21 paks, which goes down past the bottom of the window, in that folder will automatically crash it. Could you please look into a work around like either having a scroll bar or having the ability have paks split up in a pages system? Thanks.

**Comment by haxpor** [comment]
Please identify which build is this? Anything in log file you can share?

I tested this with more than 21 paks and it runs fine without crash on recent build.

By the way, next time please use the issue template as it contains kind of questions to acquire information to narrow down further the problem. Thanks.

**Comment by Computerlabrat** [comment]
It's v3 build 6510 for Windows, I believe. Also, sorry about that. Anyway, what I've noticed is scrolling past the box on the left side when picking a pak causes it crash before it can launch. I estimate that to be about 19 games.
For over 18 paks, the log file says:
Total Ram: 34321707008 Bytes
 Free Ram: 21182226432 Bytes
 Used Ram: 6000640 Bytes

debug:nativeWidth, nativeHeight, bpp, Hz  1920, 1080, 24, 60
For the over 21 paks, it was:

Total Ram: 34321707008 Bytes
 Free Ram: 21156073472 Bytes
 Used Ram: 5996544 Bytes

debug:nativeWidth, nativeHeight, bpp, Hz  1920, 1080, 24, 60


********** An Error Occurred **********
*            Shutting Down            *

Out of memory!
Allocation of size 768 failed in function 'readgif' at source/gamelib/loadimg.c:674.

Not sure how much that helps or not. It doesn't seem like much to go on.

**Comment by Computerlabrat** [comment]
I probably should have included this earlier. Maybe it could provide some more info.

[DxDiag.txt](https://github.com/DCurrent/openbor/files/3316549/DxDiag.txt)

**Comment by haxpor** [comment]
Hey @Computerlabrat , thanks for additional infothe fix about crashing in menu when you have several of pak files has been fixed since build 6649. I checked on chronocrash forum, and there's no recent build available yet that would satisfy your need.

In the meantime, you can try latest build (Build 7061, commit hash db5f083) I built for you while waiting from official build: [OpenBOR.zip](https://github.com/DCurrent/openbor/files/3316615/OpenBOR.zip)

Let me kindly ping @msmalik681. Is it possible to proceed in building recent OpenBOR build and make it available officially for user? Thanks so much malik!

**Comment by msmalik681** [comment]
The thing is releases are on hold until @DCurrent has finished his big updates and moved us to version 4.0 it is really taking a long time now as a lot of bug fixes are caught up in the newer builds.  If it is ok with DC maybe we can make a beta release for now.

**Comment by DCurrent** [comment]
Sorry @msmalik681, but it is not OK. You can make dev builds and such to try bug fixes, but I don't want an official release of any kind, beta or otherwise until I can at least get the model properties done.

**Comment by Computerlabrat** [comment]
Thanks. That seems to have fixed.

**Comment by msmalik681** [comment]
Sure DC no problem.
