### ISSUE TITLE
Bindentity Bug

### ISSUE THREAD

**Issue by msmalik681** [DCurrent/openbor#166]
Description:
Bindentity will sometimes not show or maybe kill off spawned entity.

Reproduce:
load a mod with bindentity being used keep reloading the engine until the binded entity is not showing.  Now once the bug is present even if you end the stage and start it again the entity will never re appear until you fully shutdown and start the engine again.

Expected behavior:
binded entity should always be displayed.

Here is a test mod with the bug just keep loading openbor then load the first stage until the steam entity is missing from the enemy foot area.  If the entity is there shut down and load again.

test mod: https://www.mediafire.com/file/u1i7ooqvb0ba9wv/bindentity_bug.zip/file

Version:
I have tracked down the commit that caused this problem: f2c0c046b9fccceb5bce8b9e6526ac9ad73cca95

The test mod is using this commit version.

**Comment by dbaldan** [comment]
I can confirm this issue.
I use a dev build which @msmalik681 posted some time ago and I have the same issue, but only with one specific case - all the others works fine.

This is the code I use, which was changed by White Dragon back on that day:

```
	@script
	if(frame==0) {
    		void self = getlocalvar("self");
    		void e;

    		clearspawnentry();
    		setspawnentry("name", "net");
    		e = spawn();
    		changeentityproperty(e,"parent",self); // <--- ADDED
    		bindentity(e, self,0,1,30,-1,2); // <--- CHANGED
    	}
	@end_script	
```
This was working fine until I started to use that build.
If anyone has my Avengers game, pick Hawkeye (or Spider Woman on black costume), change the arrows (down down A) until you get the Net arrow and test it.

Sometimes, the net appears and stays on the enemy, but sometimes it vanish in the middle of the animation.

**Comment by DCurrent** [comment]
I was able to reproduce the bug in provided devbuild (thanks btw, that was really helpful) - it appears in ~1 out of 5 startups. However, that build was created in the midst of updating bind entity and is upstream from numerous entity changes.

I tested over thirty times with a build from current code base to confirm and the bug does not appear. Closing.
