### ISSUE TITLE
2 player doesn't work on Nvidia shield (the dpad and buttons have the same mappings for both players)

### ISSUE THREAD

**Issue by zanzabarjones** [DCurrent/openbor#169]
I'm using 2 xinput controllers on the nvidia shield,but they're being read as the same controler...so either player controls both characters making 2 player games unplayable...could you assign different keyboard inputs to the buttons and joysticks of all controllers so there would be no overlap...I've tried every build of openbor... https://developer.android.com/training/game-controllers/multiple-controllers have you guys ever considered porting it to retroarch/libretro?libretro handles controllers pretty well regardless of emulator

**Comment by nsw27** [comment]
this is same issue that the pc version has had in the past. It was fixed as far I could see if you compile latest build of engine (though there are other new bugs and issues which I have reported)

**Comment by blisstik** [comment]
Can someone please compile the latest for Android? Just need the APK. Have got the same issue with Shield seeing the same controller.

**Comment by DCurrent** [comment]
This specific issue was fixed. @Plombo is working on a more comprehensive controller update. Closing ticket.
