### ISSUE TITLE
Could you make openbor more compatible with Android tvs?

### ISSUE THREAD

**Issue by zanzabarjones** [DCurrent/openbor#170]
openbor doesn't show up on the main menu of the Nvidia shield tv etc,you have to use sideload launcher or load it from the android apps manager...if possible could you make openbor an android tv channel ,so the app and games would show up https://developer.android.com/training/tv/start ...and could you make it easier to upgrade,like the way dolphin and other emulators upgrade easily without the user having to manually delete the old app

**Comment by haxpor** [comment]
I heard you. I'll see what I can do. Seems to be trivial task to make it show up apart from UI stuff which might need more elaborated effort. At least, we can try make it show up without sideloading first.

Could you elaborate more what's happening when upgrade the app? It should normally be upgraded with new one without deletion as per my knowledge. Any error text, dialog, or anything would be great (if any).

**Comment by dbaldan** [comment]
@haxpor as far as I know, this was always that way - I never were able to update de OpenBOR app on Android. I always needed to delete the old app first and then install the new one.

**Comment by haxpor** [comment]
Ok, I think I got you.

I believe it's down to the technical stuff when official releases .apk. I highly guess it doesn't have an incremented version number from the previous; configured before release, thus Android device sees two versions as the same (as that's only information it can make use of) then refuse to do installation unless user deletes the old first.

To solve this, for official release for .apk should incorporate tracking version number which will be incremented every time for every release in `Manifest.xml` specifically `android:versionCode`.

The same when do manual build from source then upload to somewhere for your friends to download, it will face the same problem, but this case probably should be tracked its version number manually per user.

PS. I'll created a separated issue for this for easily keeping track of.

**Comment by msmalik681** [comment]
@haxpor we could match the android version code to the openbor build number.

**Comment by snyperstyle** [comment]
I cant even get it to load a pack on the new shield tv pro. It just closes out and seems to have no controller support.

**Comment by msmalik681** [comment]
@snyperstyle What build are you using ?

**Comment by snyperstyle** [comment]
Current build directly from github apk version 1.4.4 it says openbor v3.0
build in upper left corner

**Comment by msmalik681** [comment]
@snyperstyle I will look into it and see if there is anything I can do.

**Comment by snyperstyle** [comment]
Thank you so much.

**Comment by DCurrent** [comment]
@msmalik681, what is the status? Were you ever able to come up with anything?

**Comment by msmalik681** [comment]
Sorry i have been too busy to look at this i will have look over it this weekend and confirm if it can be supported.

**Comment by DCurrent** [comment]
@msmalik681 Thanks!
