### ISSUE TITLE
240p / double strike video mode

### ISSUE THREAD

**Issue by filevans** [DCurrent/openbor#173]
Hello does the Wii version have 240p (double strike) video mode? As I can't find any settings for it. If not could it be added please? As it looks absolutely awful and blurred (on a CRT anyway) and retroArch, snes 9x gx and most emulators have 240p and it is just needed for openBOR

**Comment by DCurrent** [comment]
Sorry friend, I don't see this ever happening. Although OpenBOR allows custom screen resolution, this is the author's fiat. To date the lowest res modules (including the first Beats of Rage) run at 320*240. Most are at least 480*272 widescreen and many are HD. There just isn't enough justification to support that kind of down-sampling.

**Comment by filevans** [comment]
Yes so 320x240 is 240p and 480x272 is 272p so there is no downsampling. 640x480 looks absolutely AWFUL on BOR on the Wii. 240p looks absolutely GREAT on Dreamcast / PC on CRT. it is not being downsampled in anyway. It looks like arcade game resolutions on CRT

**Comment by DCurrent** [comment]
Sorry about that - you're probably right there's no need to down-sample. But that said, 240p is not 320x240. It is standard TV definition (352x240). There isn't a single OpenBOR module in 240p, and I can promise you no one is about to make one. So one way or another you're black boxing or re-sampling in some way. @Plombo is the Wii guy, and that port is his baby. He might be interested in your request, so I've tagged him. When it comes to the Wii I have zero know-how and even less interest.

**Comment by filevans** [comment]
You can easily implement 320x240 60hz and xxx x272 50hz. So the emulator would actually be worth using. As as it stands blurred and horrid at 640x480 I for certain will never use it like that. It's better to use the ps2, PC or dreamcast versions

**Comment by filevans** [comment]
240p is any resolution with a height of 240. 320x240, 256x240, (double dragon arcade resolution) 352x240 etc etc. All of these are 240p. 240p just expresses the heights. Width is irrelevant as it can be double, triple or quadruple horizontally, it's the height that matters in this case. 240p looks absolutely superb on a CRT and that is what BOR was meant to run in, and look like 16bit / arcade games
