### ISSUE TITLE
Shadow fade range

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#18]
*SUGGESTION* (dunno if we can use github for that)

Mugen has a cool feature which I think could be cool to have in OpenBOR: _Shadow fade range._
This is how it works:

> fade.range = top_y, bot_y ;(optional)
This parameter lets you set the range over which the shadow is visible. It is used to create an effect of the shadow fading as the player gets farther away from the ground. The first value is the high level, and the second is the middle level. Both represent y-coordinates of the player. A shadow is invisible if the player is above the high level, and fully visible if below the middle level. The shadow is faded in between the two levels. If omitted, defaults to no effect (shadow is always fully visible). Take note that y-coordinate values are negative, and TOP_Y should be less than BOT_Y.

This could be great, specially when we use gfxshadow. Because it looks weird to shadows when the entities are too high.

**Comment by DCurrent** [comment]
Not a bad idea at all really, and I imagine wouldn't be too hard to implement. We'd just use current Base coordinates as the "ground".

**Comment by nsw27** [comment]
could  similar approach be done with sounds ? for example there is something in a level making a repeated looped noise, but as player continues across level and that thing is scrolled off screen the sound fades and gets louder again if player returns closer ?

Just an idea

**Comment by dbaldan** [comment]
@nsw27 this can be done using scripts

**Comment by DCurrent** [comment]
Not only can it be done, it already has been, since ~2007. All of my Golden Axe demo videos show this in action, and the code was public for several years. Anyway, let's all please keep discussions about the specific bug or request topic.

**Comment by DCurrent** [comment]
This will be handled by the enhanced drawmethod. Closing ticket.
