### ISSUE TITLE
64-bit support

### ISSUE THREAD

**Issue by msmalik681** [DCurrent/openbor#180]
I would like to support x64 architecture on the android port I thought the source code was x64 compatible but when I used some suggested compiler flags it caught errors.  I have tried to read up about correcting code for x64 compatibility but most of it went right over my head. Can anyone support with this ?

Here is a post by google with more information: https://developer.android.com/distribute/best-practices/develop/64-bit#port-32-to-64

**Comment by msmalik681** [comment]
@haxpor @DCurrent @Plombo 

Hi guys I could really use some help with this.  It seems on x64 openbor is closing down with localvars and openborconstants returning a null value.  I have noticed with the entity proprties they are cast to a "void *" on a 32bit platform it would be 4 bytes but on a 64bit platform it will be 8 bytes.  Could this be the reason we are getting null values ?

**Comment by msmalik681** [comment]
So I have narrowed down a shutdown to the collision code.  If you enable debug options and show bboxes this part of the code will cause a shutdown.

openbor.c line:16619.
draw_box_on_entity(entity, **coords->x**, **coords->y**, entity->position.z+1, **coords->width**, **coords->height**, 2, LOCAL_COLOR_BLUE, &drawmethod);

I have tested and the engine can return all the highlighted variables using printf function but it will only return them once before shutdown.  Maybe something else happens when there variables are accessed ?  The engine will also shutdown if any attack box is used. When the engine shuts down there is no reason in the log.

**Comment by Cissoubaka** [comment]
@msmalik681 did you manage to compil a 64 version? I'm interested, but got some errors during compilation (under Archlinux)

**Comment by msmalik681** [comment]
@Cissoubaka yes but this kind of question is for the forums www.chronocrash.com

**Comment by Cissoubaka** [comment]
What are the change to make it possible to compile ?

**Comment by DCurrent** [comment]
@Cissoubaka as @msmalik681 the github issue reports are not for questions and requests. Please take those to the forum as he asked. Closing ticket.

**Comment by msmalik681** [comment]
@DCurrent Cissoubaka was spamming this issue but it was a legitimate issue started by me.  Lets just leave it closed hopefully your collision rework will fix the issue I raised here.
