### ISSUE TITLE
mirror effect does not work immediatly at start of level

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#183]
http://www.chronocrash.com/forum/index.php?topic=4587.0

Have reported on Chronocrash already. seems to be a known issue.

affects all versions of Openbor. desired outcome is mirror effect should work from start of a level and not glitch

video example

www.youtube.com/watch?v=uYwJHCZ3SGc&feature=youtu.be

**Comment by DCurrent** [comment]
Reproduced and confirmed.

**Comment by fgames9000** [comment]
Buddies, is there an easy way to reproduce this issue?

**Comment by nsw27** [comment]
just make a level start with mirror I suppose ?

video example

www.youtube.com/watch?v=uYwJHCZ3SGc&feature=youtu.be

**Comment by fgames9000** [comment]
Already made by using exactly your post and videos as reference.
I created a level using your level as base, but nothing. I will continue trying, thanks.
