### ISSUE TITLE
Screen rotation for Odroid Go Advance

### ISSUE THREAD

**Issue by shantigilbert** [DCurrent/openbor#187]
**Is your feature request related to a problem? Please describe.**
Compiled a SDL version for the Odroid Go Advance, but the screen needs to be rotated

**Describe the solution you'd like**
Rotate the screen by -90

**Describe alternatives you've considered**
I tried using this "patch" with limited success 
On line 208 of sdl/video.c
```
       //SDL_RenderCopy(renderer, texture, NULL, NULL);
       static int n = -90;
       SDL_RenderCopyEx(renderer, texture, NULL, NULL, n, NULL, SDL_FLIP_NONE);
```
The screen does rotate, but the image is cut off, I think the resolution needs to be set somewhere to 480w 320h but I do not know where.

**Additional context**
I am fine if this is provided as a patch and not part of the project

**Comment by shantigilbert** [comment]
I am getting closer, I modified engine/sdl/video.c and I can now get the loading screen and in game perfectly, but the menu is still a bit cutoff, not sure why, any ideas? 

I am also using data/video.txt to choose video option 1

I know this is far from ideal, but it (kinda) works for what I need, maybe someone could clean this up a bit and make it work better? 

```
--- a/engine/sdl/video.c
+++ b/engine/sdl/video.c
@@ -205,7 +205,17 @@
 {
 	SDL_SetRenderDrawColor(renderer, 0, 0, 0, 0);
 	SDL_RenderClear(renderer);
-	SDL_RenderCopy(renderer, texture, NULL, NULL);
+	//SDL_RenderCopy(renderer, texture, NULL, NULL);
+	
+	static int W = 320;
+	static int H = 480;
+	static int n = -90;
+	SDL_Rect dstrect;
+	dstrect.x = (W - H) / 2 - 1;
+	dstrect.y = (H - W) / 2;
+	dstrect.w = H;
+	dstrect.h = W;
+	SDL_RenderCopyEx(renderer, texture, NULL, &dstrect, n, NULL, SDL_FLIP_NONE);
 
 	if (brightness > 0)
 		SDL_SetRenderDrawColor(renderer, 255, 255, 255, brightness-1);
@@ -246,7 +256,7 @@
 		if(stretch)
 			SDL_RenderSetLogicalSize(renderer, 0, 0);
 		else
-			SDL_RenderSetLogicalSize(renderer, stored_videomodes.hRes, stored_videomodes.vRes);
+			SDL_RenderSetLogicalSize(renderer, stored_videomodes.vRes, stored_videomodes.hRes);
 	}
 }
 
@@ -269,7 +279,7 @@
 	                            SDL_TEXTUREACCESS_STREAMING,
 	                            mode->width, mode->height);
 	if(!stretch)
-		SDL_RenderSetLogicalSize(renderer, mode->display_width, mode->display_height);
+		SDL_RenderSetLogicalSize(renderer, mode->display_height, mode->display_width);
 	return texture ? 1 : 0;
 }
```

**Comment by DCurrent** [comment]
Not sure friend. I focus solely on the core engine. The guys who did ports are currently MIA.

**Comment by shantigilbert** [comment]
Thanks anyways, for now this works, the menu is just an annoyance but not game breaking.  Thanks for all of your work

**Comment by Darknior** [comment]
Relly interesting, tanks, i think we will use it too on Odroid Go Advance ;)

**Comment by shantigilbert** [comment]
@Darknior great! Maybe we can find a better solution that also works for the menu. I know the Batocera guys are much more capable than me! :)

**Comment by Darknior** [comment]
Yes for sure, @susan34 or @AiRhEaD L2G are great developpers.
They plan to add it to Batocera ... maybe you can come with us to speak about it on Discord ;)
https://discord.gg/xuuMpCy

**Comment by shantigilbert** [comment]
Thanks, I've been there for a few weeks, same username :)

**Comment by shantigilbert** [comment]
I updated the patch with the one that works with the menu as well, will close this issue now. 

Thanks

**Comment by Darknior** [comment]
@DCurrent will some feature like this one can become official in OB source code or not ?
Because it can help for all the portable and phone ports...
Thanks

**Comment by msmalik681** [comment]
OpenBOR for android auto rotates based how you hold the phone but I guess a option can be added to force roatation on devices that do not have motion sensors.  This is something I will look at in the future.
