### ISSUE TITLE
Inputs broken on Switch version

### ISSUE THREAD

**Issue by bumpouz** [DCurrent/openbor#190]
## Description
Controller inputs are broken since CFW 9.0+ on Switch version. Not sure if this is even being supported at all. Cpasjuste gave us a great working version but I can find a way to message them to see if they could recompile it for the newer CFWs.

**Comment by msmalik681** [comment]
We do not offically support the switch sorry.

**Comment by dbaldan** [comment]
@bumpouz I answered the same question today by private message (was it you?).

Nintendo Switch version of OpenBOR is not an official port neither made by us, so we can't offer any support for it, sorry.
It would be better to ask directly to who had made that port.

**Comment by bumpouz** [comment]
It probably was me. I had just posted on the website as well. I'm trying to find a way to message Cpasjuste, but I can't find any message info for them on github. Thank you for replying to my message. Keep up the good work and thanks again.
