### ISSUE TITLE
Failing to build for android    

### ISSUE THREAD

**Issue by Adnan1091** [DCurrent/openbor#192]
Helllo i am using windows 7 OS. I am trying to build openbor for my android  but whenever i try to build it.It fails.For example,when i double click build,it just instantly closes.Double-clicking gradew gets stucks at CONFIGURING%50 then it gives build fail and it closes itself.Am i doing something wrong?I added both ndk and sdk paths.https://developer.android.com/ndk/downloads and android studio.

**Comment by msmalik681** [comment]
Here is a tutorial on how to setup your environment for the android build.

http://www.chronocrash.com/forum/index.php?topic=3801.msg52283#msg52283

This is not really a engine issue stuff like this belongs in the forums so I am closing this.  Please post on the forums if your having trouble setting up the correct environment I will be happy to support.
