### ISSUE TITLE
Landframe bug

### ISSUE THREAD

**Issue by msmalik681** [DCurrent/openbor#193]
There is a bug when using landframe in a animation after the character has landed any scripts run after the landframe do not work or miss behave.

in my mod I use landframe for a dive kick animation after the character lands I want to use the dasher script to slide them for a bit before they stop and getup the animation runs but they do not slide at all I tried multiple dasher scripts (now he should slide half way across the screen) once landed again the animation runs and you see the character budge a little.

**Comment by DCurrent** [comment]
@msmalik681 I cannot reproduce. @cmd and @script tags both execute following a landframe. This is a module issue - post to the forum and we can see about helping you.

https://youtu.be/wMsMV5m4ueU
