### ISSUE TITLE
lifescore issue

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#194]
# Description
Lifescore does not work. you will not recieve an extra life as soon as you reach the required score

### Reproduce
very easy to reproduce, just set lifescore and see how it does not work

### Expected behavior
once score is reached the life should be given

### Screenshots
NA

### Version
I am using PC builds, I have compiled latest GitHub version, but also use an older, stable version and still occurs... I am guessing this has been a bug for a while but not many people will know of it as most disable and don't use this feature often

## Additional context
NA

**Comment by DCurrent** [comment]
Confirmed. Probably a simple fix. I'll try to get it done along with other upcoming updates.

**Comment by DCurrent** [comment]
Retested on latest code revision. Bug is not reproducible. Closing ticket.

https://youtu.be/wrwxSO5mEJc
