### ISSUE TITLE
screenshot button doesnt work

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#195]
## Description
screenshot button does not work everytime you press it

### Reproduce
define a screenshot key and then press the button. 

### Expected behavior
A screenshot should be taken once button is pressed

### Screenshots
...

### Version
this is on compiled version of latest GitHub PC version
## Additional context
works with older, stable version so must be a recent quirk

**Comment by msmalik681** [comment]
Please stick to stable releases for now.  When DC publishes the next stable release test this again if its fixed close this issue down or report back.

**Comment by DCurrent** [comment]
Tested. Bug not reproducible as of revision https://github.com/DCurrent/openbor/commit/36c3aebd5b9726e751315bb8c88c050999a8920e. Closing ticket.

https://youtu.be/xRdVO-CooBQ
