### ISSUE TITLE
itembox is not compatible with weapon item

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#197]
I have raised this on forum

http://www.chronocrash.com/forum/index.php?topic=4819.msg66675;topicseen#msg66675

I have a touch item which has ninja stars, player is able to shoot 10... but when ammo is depleted I can hear he picks up the item again and can still shoot stars... but now it is endless and no ammo counter (shouldn't be able to do this.) if he is hit again whilst in this state he reverts back to normal

also wanted him to expend ammo when doing jumpattack but currently he can also shoot it without it costing ammo...

here is the characters weapon model

`name heros
health		100
mp 100
speed		25
type		none

parrow	data/sprites/parrow1.png -24  -172
parrow2	data/sprites/parrow2.png -24  -172

dust		dust

riseinv 	1 1
makeinv		3 0

shadow		1

modelflag 3
weapnum 1
weaploss 0

no_adjust_base 0
subject_to_wall 1
subject_to_obstacle 1
subject_to_platform 1

cantgrab	1
atchain		1

death		1
candamage	enemy obstacle

palette		data/chars/hero/a7.png
alternatepal	data/chars/hero/pal1.png
alternatepal	data/chars/hero/pal1.png

animationscript	data/scripts/enemy.c

running	50 6 3 1 1
jumpheight 7
jumpspeed 15

anim	attack
	custknife	star
	throwframe	1 80 10 10
	sound	data/sounds/swing.wav
	hitflash	blood
	@cmd	changeentityproperty getlocalvar("self") "Subject_to_Platform" 1
	delay	5
	attack	0 0 0 0 0 0 0 0 0 0
	offset	80 123
	bbox	66 38 27 83
	frame	data/chars/hero/n1.png
	delay	8
	frame	data/chars/hero/n2.png
	delay	4
	frame	data/chars/hero/n1.png
		
anim	death
@script
                void self = getlocalvar("self");
                	void	dummy;
                int iPIndex = getentityproperty(self,"playerindex"); //Get player index
 		if ((getentityproperty(self, "direction")==1)&&(frame == 0)){
		changeentityproperty(self, "velocity", -15, 0, 0);
			setglobalvar("bikermap", getentityproperty(getlocalvar("self"), "map"));
		}
		if ((getentityproperty(self, "direction")==0)&&(frame == 2)){
		changeentityproperty(self, "velocity", 15, 0, 0);
			setglobalvar("bikermap", getentityproperty(getlocalvar("self"), "map"));
		}
						if (frame == 4){
		changeentityproperty(self, "velocity", 0, 0, 0);
		}
	@end_script	
	loop	0
	sound	data/sounds/plasmashot.wav
	delay	6
	offset	64 131
	fshadow	0
	@cmd	spawn044 "alert" 1 0 580
	frame	data/chars/hero/d1.png
	frame	data/chars/hero/d2.png
	frame	data/chars/hero/d3.png
	delay	10
	frame	data/chars/hero/d4.png
	delay	50
	frame	data/chars/hero/d4.png
	frame	data/chars/hero/d4.png
	frame	data/chars/hero/d4.png
		
anim	duck
	subentity	dust
	spawnframe	1 0
	attack	0 0 0 0
	offset	80 122
	bbox	68 59 30 64
	delay	5
	sound	data/sounds/slide.wav
	frame	data/chars/hero/slide.png
	@cmd	changeentityproperty getlocalvar("self") "Subject_to_Platform" 0
	frame	data/chars/hero/slideb.png
	frame	data/chars/hero/slide.png
		
anim	fall
	loop	0
	offset	81 138
	delay	12
	drawmethod	tintmode 4
	drawmethod	tintcolor 243_35_0
	frame	data/chars/hero/pain.png
	nodrawmethod	
	offset	81 138
	frame	data/chars/hero/pain.png
		
anim	freespecial
	cancel	1 6 0 D freespecial2
	sound	data/sounds/jump.wav
	jumpframe	1 4.5 1.5 0
	landframe	6
	offset	81 127
	bbox	65 39 33 60
	attack	0 0 0 0
	delay	5
	frame	data/chars/hero/j3.png
	@cmd	keymove 3 3
	delay	10
	offset	81 127
	bbox	65 50 39 39
	frame	data/chars/hero/j3b.png
	@cmd	keymove 4 4
	delay	10
	offset	81 127
	bbox	65 39 33 60
	frame	data/chars/hero/j3c.png
	@cmd	keymove 4 4
	delay	10
	offset	81 127
	bbox	48 45 58 40
	frame	data/chars/hero/j3d.png
	@cmd	keymove 4 4
	delay	10
	offset	81 127
	bbox	65 39 33 60
	frame	data/chars/hero/j3.png
	delay	5
	@cmd	keymove 3 3
	offset	91 123
	bbox	78 39 27 75
	frame	data/chars/hero/j4.png
	@cmd	dasher 0 0 0
	offset	91 112
	bbox	78 36 27 75
	frame	data/chars/hero/j4.png
		
anim	freespecial2
	jumpframe	0 -4 1 0
	offset	80 122
	bbox	63 61 32 62
	attack	0 0 0 0
	delay	5
	frame	data/chars/hero/slide.png
	frame	data/chars/hero/slideb.png
	sound	data/sounds/slide.wav
	frame	data/chars/hero/slide.png
		
		
anim	idle
	hitfx	data/sounds/0.wav
	loop	1
	delay	6
	offset	80 134
	bbox	68 59 27 75
	frame	data/chars/hero/r1.png
	@cmd	changeentityproperty getlocalvar("self") "Subject_to_Platform" 1
	frame	data/chars/hero/r2.png
	frame	data/chars/hero/r3.png
	frame	data/chars/hero/r4.png
	frame	data/chars/hero/r5.png
	frame	data/chars/hero/r6.png
		
anim	jump
	cancel	1 6 0 J freespecial1
	cancel	1 6 0 D freespecial2
	sound	data/sounds/jump.wav
	jumpframe	0 5 1.5 0 dust
	landframe	6
	offset	84 136
	bbox	69 63 27 73
	attack	0 0 0 0
	delay	5
	frame	data/chars/hero/j1.png
	@cmd	keymove 3 3
	delay	10
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
	@cmd	keymove 4 4
	delay	10
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
	@cmd	keymove 4 4
	delay	10
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
	@cmd	keymove 4 4
	delay	10
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
	delay	5
	@cmd	keymove 3 3
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
	@cmd	dasher 0 0 0
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
		
anim	jumpattack
	custknife	star
	throwframe	1 80 30 180
	sound	data/sounds/swing.wav
	hitflash	blood
	@cmd	changeentityproperty getlocalvar("self") "Subject_to_Platform" 1
	delay	5
	attack	0 0 0 0 0 0 0 0 0 0
	offset	80 123
	bbox	66 38 27 83
	frame	data/chars/hero/n1.png
	delay	8
	frame	data/chars/hero/n2.png
	delay	4
	frame	data/chars/hero/n1.png
		
anim	pain
	jumpframe	0 -3 -3
	delay	7
	drawmethod	tintmode 4
	drawmethod	tintcolor 243_35_0
	offset	81 138
	bbox	66 53 30 85
	frame	data/chars/hero/pain.png
	nodrawmethod	
	offset	81 138
	bbox	66 53 30 85
	frame	data/chars/hero/pain2.png
		
anim	rise
	hitfx	data/sounds/0.wav
	offset	81 130
	bbox	70 59 30 71
	attack	0 0 0 0
	delay	5
	frame	data/chars/hero/pain2.png
		
anim	run
	subentity	dust
	spawnframe	1 0
	hitfx	data/sounds/0.wav
	loop	1
	attack	0 0 0 0
	delay	4
	offset	80 134
	bbox	68 59 27 75
	frame	data/chars/hero/r1.png
	@cmd	changeentityproperty getlocalvar("self") "Subject_to_Platform" 1
	frame	data/chars/hero/r2.png
	frame	data/chars/hero/r3.png
	frame	data/chars/hero/r4.png
	frame	data/chars/hero/r5.png
	frame	data/chars/hero/r6.png
		
		
anim	runjump
	cancel	1 6 0 J freespecial1
	cancel	1 6 0 D freespecial2
	sound	data/sounds/jump.wav
	jumpframe	0 5.2 1.7 0 dust
	landframe	6
	offset	84 136
	bbox	69 63 27 73
	attack	0 0 0 0
	delay	5
	frame	data/chars/hero/j1.png
	@cmd	keymove 3 3
	delay	10
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
	@cmd	keymove 4 4
	delay	10
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
	@cmd	keymove 4 4
	delay	10
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
	@cmd	keymove 4 4
	delay	10
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
	delay	5
	@cmd	keymove 3 3
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
	@cmd	dasher 0 0 0
	offset	88 136
	bbox	73 47 30 73
	frame	data/chars/hero/j2.png
		
anim	select
	delay	5
	offset	60 143
	bbox	48 53 30 85
	frame	data/chars/hero/a1.png
		
anim	spawn
@script
    if(frame==1){
      void self = getlocalvar("self");
      int MHP = getentityproperty(self, "maxhealth");
      int PIndex = getentityproperty(self,"playerindex");

      changeentityproperty(self, "name", "Hero");
      changeentityproperty(self, "health", MHP);

      if(PIndex==1){
        changeentityproperty(self, "map", 1);
      } else if(PIndex==2){
        changeentityproperty(self, "map", 2);
      }
    }
@end_script
	hitfx	data/sounds/0.wav
	offset	81 123
	bbox	0 0 0 0
	delay	5
	frame	data/chars/hero/slide.png
frame	data/chars/hero/slide.png
		
anim	special
	hitflash	blood
	energycost	100
	fastattack	1
	mponly	1
	@cmd	spawn044 "pause" 1 0 580
	@cmd	spawn044 "alert" 1 0 580
	sound	data/sounds/hyper.wav
	delay	20
	attack5	-309 -599 1599 2142 50 1 1 0 0 100
	offset	53 139
	bbox	0 0 0 0
	frame	data/chars/hero/a13.png
	attack	0 0 0 0
	frame	data/chars/hero/a13.png
		
anim	walk
	hitfx	data/sounds/0.wav
	loop	1
	attack	0 0 0 0
	delay	5
	offset	80 134
	bbox	68 59 27 75
	frame	data/chars/hero/r1.png
	@cmd	changeentityproperty getlocalvar("self") "Subject_to_Platform" 1
	frame	data/chars/hero/r2.png
	frame	data/chars/hero/r3.png
	frame	data/chars/hero/r4.png
	frame	data/chars/hero/r5.png
	frame	data/chars/hero/r6.png
		
#|edited by openBor Stats v 0.67
		
`

here is the touch item

`name	starorb
#health	0
type	item
subtype    weapon
weapnum    1

typeshot	  1
#counter           3  
shootnum 10
falldie 1
weaploss 0

nolife 1

#subject_to_obstacle 0
subject_to_platform 0
subject_to_gravity 0
offscreenkill 300

palette data/chars/misc/star/starorb.png

anim spawn
delay	1
	offset	40 78
itembox 0 0 0 0
bbox 0 0 0 0
frame	data/chars/misc/star/starorb.png

anim death
delay	10
	offset	40 78
itembox 0 0 0 0
bbox 0 0 0 0
frame	data/chars/misc/star/starorb.png
frame	data/chars/misc/star/starorb.png

anim fall
delay	10
	offset	40 78
itembox 0 0 0 0
bbox 0 0 0 0
frame	data/chars/misc/star/starorb.png
frame	data/chars/misc/star/starorb.png

anim	idle
	loop	1
	delay	30
	offset	40 78
	itembox	2 5 74 74
	jumpframe	1 0 1.8 0
	drawmethod	tintmode 1
	drawmethod	tintcolor 100_100_200
	frame	data/chars/misc/star/starorb.png
	nodrawmethod	
	frame	data/chars/misc/star/starorb.png
		
#|edited by openBor Stats v 0.67
		
`

here is the ninja stars that are to be thrown

`name	star
type	none
shadow	0
nolife  1 
candamage enemy

offscreenkill 5
lifespan 3

anim	idle
	hitflash	blood
	loop	1
fastattack 1
	delay	5
	offset	15 13
	attack	-1 -2 33 26 80 1 1 0 0 50
	frame	data/chars/misc/star/1.png
frame	data/chars/misc/star/2.png
		
#|edited by openBor Stats v 0.58
		
`

Probably never noticed by others as many dont use itembox and touchitems for weapon pickups

when item is depleted shouldn't it play death animation ? not respawn? because then even with a high spawn delay wouldn't it then still eventually be touched again once it reaches idle... This is why I always thought they just played death anim.

Expected behaviour: you approach the touch item (starorb) you are changed to your model (heros) and can fire stars which are depleted each time you attack or jumpattack. then starorb should appear and play death animation.

Have tested on PC with older/stable versions as well as new version.

**Comment by danielt3** [comment]
Do you mind preparing a small PAK file that reproduces the problem and sending here with instructions? I'll take a look!
