### ISSUE TITLE
Optimizations for small ARM systems

### ISSUE THREAD

**Issue by vanfanel** [DCurrent/openbor#198]
Hi there,

I have just built OpenBOR on GNU/Linux for the first time, and it looks great with the PAKs I have tried so far!
But for it is fairly slow with games like He-Man.
Thing is, these hi-res games could have 2x filters removed, and only leave the SDL2 bilinear filtering that costs ZERO CPU and avoids shimmering.
However, I can not find an option in those games so far to NOT do any scaling in software (bilinear is done in software too!) and disable 2x scaling (scaling must be done in hardware too in these small ARM systems like Raspberry Pi).

So, is it possible at all as things are?
Thanks!

**Comment by msmalik681** [comment]
We do not offically support the pi but there is a unofficial port floating around the net.

But just to confirm are you using the linux port on a arm based linux os ?

**Comment by DCurrent** [comment]
Almost a year and still did hear back from original reporter. Closing issue.
