### ISSUE TITLE
Building on non-x86 systems

### ISSUE THREAD

**Issue by vanfanel** [DCurrent/openbor#199]
Hi there,

Its my plan to try OpenBOR on small ARM systems, like the popular Raspberry Pi.
However, it seems impossible to build ATM:

```
pi@raspi:~/src/openbor/engine$ ./build.sh 4
-------------------------------------------------------
OpenBOR v3.0 Build 1 (commit hash: 7a45a22) - http://www.ChronoCrash.com

All rights reserved.
See LICENSE and README within OpenBOR root for details.

Copyright (c) 2004 - 2018 OpenBOR Team
-------------------------------------------------------
-------------------------------------------------------
     ERROR - Linux x86 Environment Failed
                 SDK Installed?
-------------------------------------------------------

```

What SDK does it mean? My system as SDL2 dev headers installed and of course gcc 9.x and all other needed libs.
Does OpenBOR use x86-only code of some kind?

**Comment by msmalik681** [comment]
To compile 32bit use:
./build.sh 4 x86

For 64bit use:
./build.sh 4 amd64

Linux ARM acitecture is not really supported right now.

**Comment by danielt3** [comment]
OpenBOR is portable accross several target platforms. This does not mean its build system is ported to all of them. This is a very common mistake: being able to compile source code **for** a particular platform (OS + underlying hardware) does not mean at all that one can compile source code **on** that particular platform.

If you just need to build OpenBOR **for** Rasp you have a moderately easy path using a cross-toolchain and hosting the build on a Linux box. Building OpenBOR **on** Rasp is way more difficult: you need to port the entire build environment to the Rasp and make it work there.

Please note that even though OpenBOR can be **run** in several platforms, from what I can understand you can host the build in Windows, Linux and MacOS only.

**Comment by DCurrent** [comment]
@danielt3 explained this very well. Closing ticket.

**Comment by vanfanel** [comment]
@danielt3 That's a very nice explanation indeed! The message had slipped through my queue, sorry.
Thanks! It's clear now :+1: 
Are there instructions on how to setup a cross-compilation enviroment for this? Or should a generic Pi4 cross-compilation enviroment do?
