### ISSUE TITLE
OpenBOR for official Debian GNU/Linux packaging

### ISSUE THREAD

**Issue by coringao** [DCurrent/openbor#2]
I'm interested in working with this source code to make it available in Debian repositories to give more visibility to GNU/Linux user.

But you would like to understand better in the compilation could you clarify me?

![captura de tela de 2017-05-01 19-16-46](https://cloud.githubusercontent.com/assets/289377/25597026/c294b0d4-2ea2-11e7-9b13-2f7a9efb0e6e.png)

Saying that did not find the files for compilation, could you tell me what I'm doing wrong?

Thanks!

**Comment by DCurrent** [comment]
After you run build.bat, you'll need to go into the tools folder. In each platform you'll find a the compressed tool chain, and an uncompressed tool chain. Move the contents of the uncompressed folder into the platform folder. Then try running the build.bat again. You're good to go from there forward.

I need to get that fixed, but haven't gotten to it yet.

**Comment by coringao** [comment]
Thanks for the tips.
I made a compilation and found a simple error, which I solved.

> openbor.c: In function 'didfind_item':
> openbor.c:27468:50: error: self-comparison always evaluates to false [-Werror=tautological-compare]
>              if(self->weapent->modeldata.shootnum **>** self->weapent->modeldata.shootnum)
> 
> In this line replaces this:
> openbor.c:27468:50: if(self->weapent->modeldata.shootnum **&&** self->weapent->modeldata.shootnum)

[compilation.txt](https://github.com/DCurrent/openbor/files/969102/compilation.txt)

**Comment by coringao** [comment]
It worked perfect, now I need to study the source code better.

![captura de tela de 2017-05-01 22-12-59](https://cloud.githubusercontent.com/assets/289377/25600633/07b0d490-2ebc-11e7-82b6-9a72829d6f13.png)

**Comment by DCurrent** [comment]
Cool, though keep in mind I'm in the midst of some major additions and clean up. You should jump into the community @chronocrash.com and join up. I'm going to go ahead and close the ticket. Let me know if you have any other issues.
