### ISSUE TITLE
OGG files over BOR

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#20]
Any plans to fix the issue with REMIX.BOR? [I reported it back at 2013. ](http://www.chronocrash.com/forum/index.php?topic=1001.msg12988#msg12988)
There is a required music: remix.bor. If you put a remix.ogg it will play, but when you go back to the title, it will play the .bor version instead.

It would be better if the engine can look for .ogg files in all required music, since .ogg is way smaller than .bor

**Comment by DCurrent** [comment]
The better solution is to not require music and sounds in the first place. That's an author's perogative.

**Comment by DCurrent** [comment]
@dbaldan I just checked the code and there is no requirement for remix.bor. The engine just looks for .bor, and then .ogg version. You should just be able to remove the .bor and .ogg will always play.
