### ISSUE TITLE
Very difficult to find resources

### ISSUE THREAD

**Issue by averagehat** [DCurrent/openbor#207]
currently if I go to the main page of the wiki, I navigate to the manual and see a statement from 2017 that the manual is outdated. But it appears to have been updated a number of times since then.

There seem to actually be a lot of resources for working with and learning about openbor. But they are really hard to find. I worry that a lot of folks won't be as persistent as me and will give up on trying this tool because it is hard to figure out what the heck to do with it. That would be a shame because it seems, so far, to be in many ways very powerful and easy to use compared to other options.

This problem wouldn't be so bad if the chrono crash site wasn't limited. The search feature on the site is difficult to make useful because it is so limited. For example I searched "wiki" and got > 300 results, the top result is from 2013, and there is no way to sort by time of post. Additionally, I had to create an account to search in the first place, which creates more friction for new people.

## Examples
Additionally, I could only find a few projects by @DCurrent as examples. I encountered references to decompiling pak files, but without any information on what they were or what the result would be. I eventually found many downloads (which could serve as eamples) on the chrono crash site.

## Tooling: 
For a long time I assumed that there was no editor for the tool. I found references to one which has expired; eventually I found mention of fighting factory,etc. And
I also found people referencing an "edit pack" which I found on a downloads page of the chrono crash site--I have no idea how I found that downloads page. I had no idea that was on the site.

## Learning 
There are a number of tutorial stickies on the chronocrash site. I appreciate this but this is again scattered information with no "getting started" guide, and no differentiation between what is out of date and what isn't.

## The Wiki
The only other parts of the wiki I can find are about specific use cases of scripting and very basic information about scripting variables. It is difficult to use this as a beginner because these are just scattered pieces of information without any context.

Suggestions:
 - have some up-to-date document that is linked from github 
 - Link to the wiki from the readme
 - Link to the discord channel somewhere 
 - make it clear what content on the wiki is up to date and what isn't
 - the rest should be clear from my comments above 
 - improvements to the chrono crash site would be great but that seems like a stretch

**Comment by DCurrent** [comment]
@averagehat, this really isn't an appropriate venue for that kind of discussion. This is for issues specific to engine itself, not using it. Therefore I'm going to close and lock this. You are welcome to continue it at the forum.

Documentation is always going to be a problem with user content driven software. When was the last time you saw a comprehensive manual for MS Word, SQL, or Access? Hint: There isn't one. Just hundreds of knowledge base articles by MS, books, tutorials, classes, etc.. I notice the same issue with Unity, Godot, and so on. Those people have vast amounts of resources and they can't do it. OpenBOR is every bit as complex and versatile as those applications (arguably more so). How do you expect a three person crew (only yours truly being regularly active) to?

We'd love to have a singular, well organized guide, and several attempts have been made, the wiki one of them. But inevitably we run into the same catch-22. Anyone who knows what they're doing doesn't have time, and anyone who has time doesn't know what they're doing. What we do have is an active community of people will to help and guide you. Of course we require account registration or else the bots would overrun us and leave 0 bandwidth for real people. If you think that's too much friction, I'm not sure what else i can offer.

I know that's not what you want to hear but it's all I can offer for the moment.

DC
