### ISSUE TITLE
Neon panels removes shadows from a stage

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#208]
When placing a neon-type panel on a stage, the shadow of all entities is removed.

### Reproduce
When I set no neon parameter, the shadow is displayed normally
> background      data/bgs/factoryb/background.gif none none
> panel	        data/bgs/factoryb/ground.gif none none
> frontpanel	data/bgs/factoryb/front.gif none none
![Image ](https://i.imgur.com/p5F1VZx.png)

But if you set the neon parameter, the shadows are gone
![Image ](https://i.imgur.com/lg4dqkH.png[/img)

### Expected behavior
The shadows should appear. I haven't tested with normal shadows, only with gfxshadow

### Version
Windows - 6315, 6330, Private July20 build

**Comment by DCurrent** [comment]
Tested and confirmed. Not sure if I can fix it without breaking a bunch of other stuff though. The neon code is really, really old and embedded.

**Comment by dbaldan** [comment]
I will try to pinpoint which version build started to break this.
