### ISSUE TITLE
getentityproperty / changeentityproperty

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#21]
Guys, I want to document all the entity properties but I need help with that, so I would like to ask help from the Devs. There are some properties which I never heard about, like _"trymove", "link",_ etc.

Some of them seams self explanatory or easy to understand, but some aren't. 
Any help is very appreciated.

**~Property names:**
"a" - Altitude (deprecated)
"aggression" -
"aiattack" -
"aiflag" -
"aimove" -
"alpha" - Channel for sprite fusion. From 0 to 6.
"animal" -
"animating" - In return 0 if the entity isn't in animation (static frame), 1 if animation forward (from 0 to X) and -1 if animating backward (from X to 0). Example AI enemies when walking back have "animating" == -1.
"animation" - The handle of current animation.
"animation.handle" -
"animationid" - The id of current animation. It is an integer value, see 'openborconstant'.
"animheight" -
"animhits" - The internal hit counter for current animation.
"animnum" - Is the "animationid"
"animpos" - Frame position of current animation.
"animvalid" - It returns 1 if animation exists in entity.txt
"antigrab" -
"antigravity" -
"attackid" -
"attacking" - Entity's attack box status. When 0, attack box will not hit other entities.
"attackthrottle" -
"attackthrottletime" -
"autokill" -
"base" - Altitude base where is the entity on, if a equals base, this entity is in air.
"bbox" -
"blink" -
"blockback" -
"blockodds" -
"blockpain" - Entity blockpain property. If intended damage from blocked attack >= blockpain, entity will briefly twitch or play Blockpain animation if it has one.
"boomerang" - changeentityproperty(entity,"boomerang",acceleration,horizontal_distance) and getentityproperty(entity,"boomerang",flag) -> flag: 0 = acceleration, 1 = horizontal_distance
"boss" -
"bounce" -
"bound" -
"candamage" -
"chargerate" -
"colourmap" -
"colourtable" -
"combostep" -
"combotime" -
"custom_target" - If set it you can force an enemy to use it as target.
"damage_on_landing" - Damage that will be applied at end of a fall. If -1, entity will instantly recover at end of fall and play "land" animation if it has one.
"dead" -
"defaultmodel" - Model name base (no weapon name)
"defaultname" - Model name base (no weapon name)
"defense" - Return one of the defense factors of this entity. Follow by an integer specifies the attack type(see 'openborconstant', and also 'changeentityproperty').
"destx" - Destination of coord X for A.I.
"destz" - Destination of coord Y for A.I.
"detect" - Entity's stealth detect factor.
"direction" - Direction, 1 means left, 0 means right.
"dot" -
"dropframe" -
"edelay" -
"energycost" -
"escapecount" -
"escapehits" -
"exists" - Well, whether the entity is a valid one.
"facing" -
"falldie" -
"flash" -
"freezetime" -
"frozen" -
"gfxshadow" - This is the flag to set gfxshadow
"grabbing" - Entity currently held in a grab (if any). Only returns currently held entity.
"grabforce" -
"guardpoints" -
"hasplatforms" - It returns 1 if the entity you set is has a platform in current animation
"health" - Current HP left.
"height" - Height of a entity. If not set, you can't hit the latform with head.
"hitbyid" -
"hitheadplatform" - It returns the platform handler if the entity hit the platform with head and set the entity height > 0
"hitwall" - It returns 1 while you hit a wall/obstacle/platform while y > base
"hmapl" - Start index of hidden maps that you set with hmap X Y.
"hmapu" - End index of hidden maps that you set with hmap X Y.
"hostile" -
"icon" -
"iconposition" -
"invincible" -
"invinctime" -
"jugglepoints" -
"jumpheight" -
"jumpmovex" -
"jumpmovez" -
"jumpspeed" -
"knockdowncount" -
"komap" -
"landedplatform" - It returns the platform handler where the entity is on if entity is on, otherwise it returns NULL()
"landframe" -
"lifeposition" -
"lifespancountdown" -
"link" -
"map" - Current color remap in use. 0 = default, 1 = first remap, and so on.
"mapcount" - Number of maps
"mapdefault" -
"maps" -
"maptime" -
"maxguardpoints" -
"maxhealth" - Max health.
"maxjugglepoints" -
"maxmp" - Max MP.
"model" - Model name.
"mp" - Current MP left.
"mpdroprate" -
"mprate" -
"mpset" -
"mpstable" -
"mpstableval" -
"name" - Current name, or we say alias.
"nameposition" -
"nextanim" -
"nextmove" -
"nextthink" -
"no_adjust_base" -
"noaicontrol" -
"nodieblink" -
"nodrop" -
"nograb" -
"nohithead" - set nohithead 1 in entity.txt and even if you set an height for the entity, if it hit a platform with nohithead param set to 1, the entity will not block with head by a platform. But this platform will be walkable however. default is 0
"nolife" -
"nopain" -
"numweapons" - It returns the number of weapons of the entity.
"offense" - Return one of the offense factors of this entity. Follow by an integer specifies the attack type(see 'openborconstant', and also **'changeentityproperty').
"offscreen_noatk_factor" - set the chance (you need 1.0) has the enemy to attack offscreen. if you set 1.0 (NO ATK FACTOR) the enemy will not attack offscreen
"offscreenkill" - set after how many pixels offscreen the enemy can die
"opponent" - Last entity interacted with (damaged, damaged by, grabbed, etc.). Essentially this returns whoever would be showing up on a player's enemy life meter, but works for all entities.
"owner" -
"pain_time" -
"parent" -
"path" -
"pathfindstep" -
"playerindex" -
"position" -
"projectile" - Entity's projectile (blasted or thrown) status. 0 = Normal, 1 = Blasted or thrown.
"projectilehit" -
"range" -
"releasetime" -
"running" -
"rush_count" - current rush count
"rush_tally" - max rush count
"rush_time" - how much time you have before rush has ended.
"score" -
"scroll" -
"seal" - Entity's seal property. Entity cannot perform any special with an energy cost >= seal property.
"sealtime" - The elapsed gametime when engine will reset seal property to 0.
"setlayer" -
"shadowbase" -
"sortid" -
"spawntype" -
"speed" -
"sprite" -
"spritea" -
"stalltime" -
"stats" -
"staydown" -
"staydownatk" -
"stealth" - Entity's stealth factor.
"subentity" -
"subject_to_basemap" -
"subject_to_gravity" -
"subject_to_hole" -
"subject_to_maxz" -
"subject_to_minz" -
"subject_to_obstacle" -
"subject_to_platform" -
"subject_to_screen" -
"subject_to_wall" -
"subtype" - Subtype, e.g., arrow, biker. It is an integer value, see 'openborconstant'.
"takeaction" -
"think" -
"thold" -
"throwdamage" -
"throwdist" -
"throwframewait" -
"throwheight" -
"tosstime" -
"tossv" - Toss velocity (jumping or falling).
"trymove" -
"type" - Type, e.g, enemy, player. It is an integer value, see 'openborconstant'.
"velocity" - Set the velocity. It accepts 3 params. NULL() is valid.
"vulnerable" -
"walkoffmovex" -
"walkoffmovez" -
"weapent" -
"weaploss" - It accepts to values, example: changeentityproperty(entity,"weaploss",1,0). For first value see weaploss {flag} for second set the flag active on/off
"weapnum" - Set/get the weapon index
"weapon" - Set/get the weapon index but it accepts a second param, anim_flag: if set to 1 for scripted midair weapon changing, default 0
"x" - X position in level.
"xdir" - Horizontal velocity.
"y" - Altitude position in level.
"z" - Z position in level.
"zdir" - Vertical velocity.

**Comment by DCurrent** [comment]
Well for one thing, every last one of those is about to go defunct. Since I am off all this week, I'm getting back into my entity/animation property project which will replace all the text property names with integer constants, and eliminate the horrendously awful sub-property mess (MUCH faster, and enable other tricks not possible now). 

You'll use named constants to access the properties: Think: set_entity_property(openborconstant("PROP_NAME"), <value>)

Sub properties will work the same way, you just get the parent collection first, be accessed by getting the parent collection first.

**Comment by DCurrent** [comment]
This is now a legacy function set as the new one will be coming online soon, and it has [ full documentation](http://www.chronocrash.com/apps/wiki/obor/index.php?title=Entity_Property_(Scripting)). Closing this ticket.
