### ISSUE TITLE
Fails to compile due to a missing closing ), fix included

### ISSUE THREAD

**Issue by shantigilbert** [DCurrent/openbor#214]
## Description
Compiling fails on latest master: 

```
source/gamelib/packfile.c:496:69: error: expected ')' before '{' token
     if((handle = open(packfilename, O_RDONLY | O_BINARY, per) == -1)
       ~                                                             ^
                                                                     )
     {
     ~                                                                
source/gamelib/packfile.c:588:1: error: expected expression before '}' token
 }
 ^
```

## Debugging
As compiling error says, it just missing a `)`, adding it makes it compile fine. 

https://github.com/DCurrent/openbor/blob/d9ff4596baad6da6e1bbd1002bc9879974ff365d/engine/source/gamelib/packfile.c#L496

should be `if((handle = open(packfilename, O_RDONLY | O_BINARY, per)) == -1)`

### Reproduce
Clean compile latest master

### Expected behavior
Finish compiling :)

**Comment by msmalik681** [comment]
My bad i will fix right away

**Comment by DCurrent** [comment]
I noticed this myself and fixed it in code. Guess I forget to merge, ooops. Closing since @msmalik681 fixed.
