### ISSUE TITLE
Edge command not working ?

### ISSUE THREAD

**Issue by nsw27** [DCurrent/openbor#215]
I have a endless running ninja game ive been working on for ages and tested in the current PC version I compiled.

In current version edge command does not work at all.

expected behaviour (at the edge of a platform player is to perfrom edge animation)

occuring behaviour (player just does normal idle)

This was a great trick beacuse I made platforms and duplicated them so when player is on the platform it thinks its edge so if you arent walking I had the edge animation as a crouch and it would scroll and move player back to left of screen. Now he just stays in idle runs on spot and the illusion of forward momentum of stage is ruined.

I went back and fourth with version I normally use and the current build, can provide example videos like I have in past or if easier can send through my game to you DC if needed.

**Comment by DCurrent** [comment]
@nsw27, do you know what version this started? Also, yes, a test module would help greatly. I just ran into a 10 alarm issue at work, but will get to this soon as I can.
