### ISSUE TITLE
OpenBor doesn't launch on windows 7 x 64!

### ISSUE THREAD

**Issue by ddylard** [DCurrent/openbor#218]
## Description
I wanted to try Silver Knights Crusaders pak but the game wont launch in windows 7. i tried the latest alpha 4.0 and several older versions but none will launch. i also get no errors poping up and cant get help anywhere on the internet because nobody seems to have this issue....thanks!
### Reproduce
run openbor.exe and nothing happens.

### Expected behavior
see the program running

### Version
4.0 and 3.0
- Platform PC windows 7 SP1  x64
- Engine Build 4.0 and 3.0

**Comment by danielt3** [comment]
Please, send a link to the PAK also so we can try to reproduce the problem in the same environment you have.

**Comment by danielt3** [comment]
Did you checked the log to see if there is some insight?

**Comment by ddylard** [comment]
i am sorry for the late reply Danielt3 but the good news is i solved the problem and now the game is working perfectly. i will explain what was happening and how i got it solved because i figure it can be the problem for many people trying to launch openBOR and not being able to without any error messages.

I went to check the OPENBOR log file wich is located in the openbor folder itself and it turns out i was getting a sound error. Something like: CANT FIND "DSOUND" ENTRY or something like that.

I must clarify i have found similar errors on DOSBOX emulator and KRONOS saturn emulator and the solution is as follows:

you must right click your SYSTEM FOLDER and click PROPERTIES. 
Now you have to click on Advanced configuration from the left panel.
Now you have to click on Environment Variables which is located at the very bottom of the tab.
Now in SYSTEM VARIABLES you need to find the variable called SDL_AUDIODRIVER.

In my case its value was "dsound" or direct sound which was what openbor couldn't find. Changing its value to "winmm" did the trick.

I must clarify that if some application stops "sounding" this is probably the reason and you need to change the setting back to its previous value. For me it's only those two emulators and now openbor that need this option either on one value or the other. 

Hoping i was clear i would like to thank you guys and hope this helps somebody in the future.

;)

**Comment by DCurrent** [comment]
Thanks @ddylard! I'll mark this as closed.
