### ISSUE TITLE
Common configuration file suggestion

### ISSUE THREAD

**Issue by mikewalshchicago** [DCurrent/openbor#219]
**Is your feature request related to a problem? Please describe.**
Controller and display settings need to be configured for each PAK individually.  

**Describe the solution you'd like**
If OpenBOR looked for a .CFG file that matched the name of the .EXE instead of the .PAK, one could put multiple PAKs in the appropriate folder, and OpenBOR woiuld always use the same config.

**Describe alternatives you've considered**
Most of the suggestions and solutions for this issue that I see in the forums are to write or use a script that will copy a existing .CFG and rename it to the PAK name,or do the same manually.  Even when partially automated this process is daunting, and gets rather tricky when the games are archived in 7z.  

**Additional context**
Although I understand the potential issues of using a CFG that was intended for a different game on a PAK or the application, I think this is easier for users to manage than a CFG for each PAK.  For example, I would suggest that users who intend to use a common CFG create different executables based on the games characteristics, for example OpenBOR2players.exe and OpenBOR4players.exe.

With some guidance I'm willing to try to prototype this via a pull request if you don't have the time or are not convinced this is a viable solution.  I just need to understand the mechanics of the CFG file and what prompts OpenBOR to use it.  A bit tricky for me to reverse engineer, even with the code right in front of me, as the CFG files are in binary.

**Comment by DCurrent** [comment]
@mikewalshchicago,

I'm not 100% sure either way myself. I never use joysticks or any of the ports, so I really don't have a dog in the fight. Truth be told, I've never touched the CFG files and don't really know how they work myself. You're welcome to poke around and make a pull request - I'll add you as a contributor, but you'll need to get a consensus in the forum before I can approve a functionality change like this.

**Comment by mikewalshchicago** [comment]
Hey, thanks for replying.  Looks like a pull request wont be necessary, as it's already in the code:

void saveasdefault()
{
#ifndef DC
    FILE *handle = NULL;
    char path[MAX_BUFFER_LEN] = {""};
    getBasePath(path, "Saves", 0);
    strcat(path, "default.cfg");
    handle = fopen(path, "wb");
    if(handle == NULL)
    {
        return;
    }
    fwrite(&savedata, 1, sizeof(savedata), handle);
    fclose(handle);
#endif
}

I can create a default.cfg by 
1. starting any pak
2. adjusting my settings to my liking
3. closing the game
4. renaming the .cfg file in the saves directory to default.cfg
5. profit

I must have missed this in the documentation, and I had assumed the default cfg was the bor.cfg that is created when compiling the source.  Anyway, the more you know!

**Comment by DCurrent** [comment]
@mikewalshchicago, thanks. I'll close this for now.
