### ISSUE TITLE
Recursive spawns

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#23]
**Suggestion**
I would like to sugest the engine to be able to use recursive spawns. Right now, if you have an entity and want it to spawn another copy of itself in a different animation (so you can spawn parts of his body, for example), the spawn function go crazy, with the entity spawning in very weird places, like outside of the walkable area, wrong animation, etc

I am using this function to spawn:

> void spawnAni(void vName, float fX, float fY, float fZ, void Ani, float Vx, float Vy, float Vz)
> {
> 	//spawnB (Generic spawner) + Specific animation + velocities
> 	//Damon Vaughn Caskey + Douglas Baldan
> 	//07/06/2007
> 	//
> 	//Spawns entity next to caller.
> 	//
> 	//vName: Model name of entity to be spawned in.
> 	//fX: X location adjustment.
> 	//fZ: Y location adjustment.
>       //fY: Z location adjustment.
> 
> 	void self = getlocalvar("self"); //Get calling entity.
> 	void vSpawn; //Spawn object.
> 	int  iDirection = getentityproperty(self, "direction");
> 
> 	clearspawnentry(); //Clear current spawn entry.
>       setspawnentry("name", vName); //Acquire spawn entity by name.
> 
> 	if (iDirection == 0){ //Is entity facing left?                  
>           fX = -fX; //Reverse X direction to match facing.
> 	}
> 
>       fX = fX + getentityproperty(self, "x"); //Get X location and add adjustment.
>       fY = fY + getentityproperty(self, "a"); //Get Y location and add adjustment.
>       fZ = fZ + getentityproperty(self, "z"); //Get Z location and add adjustment.
> 	
> 	vSpawn = spawn(); //Spawn in entity.
> 
> 	changeentityproperty(vSpawn, "position", fX, fZ, fY); //Set spawn location.
> 	changeentityproperty(vSpawn, "direction", iDirection); //Set direction.
>     performattack(vSpawn, openborconstant(Ani)); 
> 	changeentityproperty(vSpawn, "velocity", Vx, Vy, Vz);
> 
> 	return vSpawn; //Return spawn.
> }
> 

Tested in OpenBoR v3.0 Build , Compile Date: Dec 22 2016 - OpenBOR_v3.0_Build_4419

**Comment by dbaldan** [comment]
@whitedragon0000 take a look at this too :)

**Comment by whitedragon0000** [comment]
I know that the recursive spawning is not enabled for a protection crtieria.
It's right, if you use a recursive spawn it becomes useless and you will enter in a loop freeze.
So you need to spawn ANOTHER entity.
You function has 2 issues.
First check for fx,fz,fy NULL() values...
Example: if ( fX == NULL() ) fX = 0; etc....
then perform an attack with reset flag like:
performattack(vSpawn, openborconstant(Ani), 1);
Then is you have some issues you try to call performattack(vSpawn, openborconstant(Ani), 1); from frame with index >= 1
Byeeee

**Comment by dbaldan** [comment]
@whitedragon0000 So it's impossible to do without using another entity?

About my function, why I need to check for null first? And that part was not my code.

**Comment by DCurrent** [comment]
@dbaldan look at the date, I whipped that function up as a test over ten years ago when OpenBOR first gained script functionality. It was never meant to be used in production, and yet still floats around to this day, lol. It's always best practice to sanitize arguments - otherwise you can get undefined results.

Lets make sure we're on the same page. I'm assuming by "entity" you meant "model", and no, you don't need a second model. Like WD said, you just need to use the reset flag when you set the second entity's initial animation. You should also reset its position once spawned too - don't rely on the spawner to do it for you.

**Comment by dbaldan** [comment]
@DCurrent hehehe when I started, the scripting documentation was almost absence. So I learnt by looking at other people works. The code works anyway, lol.

I got the reset flag for the animation, but not about the positions. If I will set all the positions of the second model, why I need to reset it?

**Comment by whitedragon0000** [comment]
@dbaldan You need to reset animation tu avoid animation bugs and stucks.

**Comment by dbaldan** [comment]
@whitedragon0000 I've modified my code to include the animation reset and the check for the x,y,z NULL() values but it still doesn't work.

The entity, "Lurker", should spawn a copy of itself, on a specific animation and where I call it.

here is the code:
```
void spawnAniR(void vName, float fX, float fY, float fZ, void Ani, float Vx, float Vy, float Vz)
{
	//spawnB (Generic spawner) + Specific animation + velocities + reset
	//Damon Vaughn Caskey + Douglas Baldan
	//07/06/2007
	//
	//Spawns entity next to caller.
	//
	//vName: Model name of entity to be spawned in.
	//fX: X location adjustment.
	//fZ: Y location adjustment.
      //fY: Z location adjustment.

	void self = getlocalvar("self"); //Get calling entity.
	void vSpawn; //Spawn object.
	int  iDirection = getentityproperty(self, "direction");

	clearspawnentry(); //Clear current spawn entry.
      setspawnentry("name", vName); //Acquire spawn entity by name.

	if (iDirection == 0){ //Is entity facing left?                  
          fX = -fX; //Reverse X direction to match facing.
	}
	if ( fX == NULL() ) fX = 0;
	if ( fY == NULL() ) fY = 0;
	if ( fZ == NULL() ) fZ = 0;
	//if ( Vx == NULL() ) Vx = 0;
	//if ( Vy == NULL() ) Vy = 0;
	//if ( Vz == NULL() ) Vz = 0;
	
      fX = fX + getentityproperty(self, "x"); //Get X location and add adjustment.
      fY = fY + getentityproperty(self, "a"); //Get Y location and add adjustment.
      fZ = fZ + getentityproperty(self, "z"); //Get Z location and add adjustment.
	
	vSpawn = spawn(); //Spawn in entity.

	changeentityproperty(vSpawn, "position", fX, fZ, fY); //Set spawn location.
	changeentityproperty(vSpawn, "direction", iDirection); //Set direction.
    performattack(vSpawn, openborconstant(Ani), 1); 
	changeentityproperty(vSpawn, "velocity", Vx, Vy, Vz);

	return vSpawn; //Return spawn.
}
```
Them I call it: 
@cmd spawnAniR "Lurker" 0 0 1 "ANI_RISE" 0 0 0

It spawns a copy of itself, but not on the animation I set and it spawns the entity at position 0 of the stage, not where the parent is.

What I am doing wrong and how I can fix it?

**Comment by dbaldan** [comment]
@DCurrent can you take a look at this?

**Comment by DCurrent** [comment]
@dbaldan I will, but no guarantees. It's pretty low on my priority list until I can get other things cleaned up.

**Comment by DCurrent** [comment]
Closing this for now. I think this is more of a module support issue for the forum. Otherwise I'd like to get bug fixes and large projects off my plate first.
