### ISSUE TITLE
OpenBOR won't execute/Launch

### ISSUE THREAD

**Issue by DaviGamerXP** [DCurrent/openbor#231]
OpenBOR simply won't execute, i click the .exe file, and nothing happens. it just doesn't.
Only a single older version of OpenBOR worked, but it glitches with a few games, so i want to update OpenBOR but every other time i try to download and run it, Nothing happens, no matter if it has PAK files in the paks folder or not, it doesn't launch.

Using Build 6391 V3.0

PC is Windows 7 x64

Please help me if you can

**Comment by DCurrent** [comment]
@DaviGamerXP You were already given an explanation and directed to the forum by @dbaldan. These are not engine bugs. Please stop spamming superfluous bug reports or I will have to block your access to the repository.
