### ISSUE TITLE
Make the OB INI file human readable

### ISSUE THREAD

**Issue by Darknior** [DCurrent/openbor#236]
Like an exemple is better than many words  ....
The request is to make the OB INI file readable, only this file, not the save files for sure.

We already patch OB to do it, it is not a problem, but i think it can help others to make it official.
Here is the link with our patch file.

https://github.com/batocera-linux/batocera.linux/blob/95f96803e04027b7996c73ae05b40a891dad0ca9/package/batocera/emulators/openbor/openbor/002-fixkeys.patch

Like it is easier to integrate OB on a full system, with many other engine and emulators ... many users love OB and i'm one of them :)
I really wish this patch will become official :)

**Comment by Plombo** [comment]
I don't think that patch can be merged as is (it makes some unrelated changes we don't want), but I'm generally in favor of the idea of using a .ini for settings. It could improve the situation where settings data is incompatible between engine versions.

**Comment by Darknior** [comment]
> I don't think that patch can be merged as is (it makes some unrelated changes we don't want), but I'm generally in favor of the idea of using a .ini for settings. It could improve the situation where settings data is incompatible between engine versions.

Cool thanks a lot. Our solution is not the best one, it is only a fast patch to permit to integrate OB with other gamepad settings we use. To make it easier for gamers that use Batocera.
And yes we have diffèrent patch for our 4 OB builds we use ... because like you write, options are not compatible.

My request is only that OB should use a human readable INI file, it can help a lot, and we are not fan of patching soft. We prefer only use them and if possible help to improve some little options ... like we already do for some emulators.

**Comment by DCurrent** [comment]
I will look into .ini in future updates. Closing.
