### ISSUE TITLE
Sound & Playgif Glitch

### ISSUE THREAD

**Issue by DCurrent** [DCurrent/openbor#237]
## Description
Starting at commit 83525e80 in dc_unified_updates branch, engine appears to have severe issues simultaneously streaming data. This manifests most obviously as opening music stopping or playing as "radio static" when an animated .gif such as an intro sequences or logo starts to play.

### Reproduce
1. Download original BOR to ensure no scripts or other advanced techniques are to blame.
2. Open with last known good commit, d10bdc32. The module will load and play normally.   
3. Open and test with 83525e80. The opening music is garbage static or will not play at all. Logo cinematic utilizing animated .gif files will include artifacts and doubling (See screenshots). I have not tested with WebM video but presumably it will have similar issues.

### Expected behavior
Engine should have ability to stream music and .gif files simultaneously.

### Screenshots
![image](https://user-images.githubusercontent.com/5900142/126266413-89d7ddc9-81d9-4103-9d1e-82d224a53bc9.png)

![image](https://user-images.githubusercontent.com/5900142/126266007-0ceb0df1-0755-462f-b250-37db7c09940d.png)

### Version
Note versions are found in dc_unified_updates branch:

- d10bdc32 - Last known good.
- 83525e80 - Bug appears. 

There are several versions in between that do not compile due to being in progress work. They invoke minimal changes, all related to permissions in packfile.c. I have tested with changes removed and bug persisted.

**Comment by fgames9000** [comment]
I sent a code for you in the forum

**Comment by DCurrent** [comment]
You are a lifesaver @fgames9000. I knew it was something super simple, but spent hours beating my head against the wall trying to find it. Thanks again!

**Comment by Plombo** [comment]
Something tangentially related I discovered looking at the commit 83525e8 you mentioned is that you forgot to change "per" to "file_permission" on line 466, and Linux compilation is broken on your branch as a result.

**Comment by fgames9000** [comment]
Yeah, Plombo is right. Sorry man, I didn't test Linux build

**Comment by DCurrent** [comment]
@Plombo & @fgames9000, thanks for the catch. I'll get that fixed.
