### ISSUE TITLE
Skipselect resets the life count

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#24]
As reported [here](http://www.chronocrash.com/forum/index.php?topic=3610.0), if you use skipselect -
 with or without parameters - between two levels, the engine will ignore how many lives you have and reset it to the default value informed in the set.

OpenBoR v3.0 Build , Compile Date: Dec 22 2016 - OpenBOR_v3.0_Build_4419

**Comment by dbaldan** [comment]
I've made a temporary fix using scrips here: http://www.chronocrash.com/forum/index.php?topic=3610.msg50090#msg50090

But I believe this should be fixed in the source code.

**Comment by whitedragon0000** [comment]
fixed!

**Comment by dbaldan** [comment]
@whitedragon0000  thanks, I will take a look.
