### ISSUE TITLE
Drawmethod Clip

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#26]
Seams that Drawmethod Clip has an issue: The effect isn't replicated by the gfxshadow neither by the mirror effect, as show on the image bellow.

![avengers - 0026](https://user-images.githubusercontent.com/31666009/36073897-fda9c706-0f1e-11e8-8678-538d4b7b0131.png)

The gfxshadow still shows the normal sprite shadow (when it should show only the clipped part) and the mirror simply doesn't shows the sprite at all.

Also, can one of the devs documents Drawmethod Clip?

> drawmethod clip {x} {y} {w} {h}
> ~This one is on svn but is still experimental.

The X and Y starts counting from where? The image edge or from the image axis?
The W goes from left to right, but the H starts trom top to down or bottom to top?

Edit: I got it. It starts from the image edge, at top left. I will add this into the manual.

**Comment by dbaldan** [comment]
More info:
When you use a Drawmethod Clip, you can't chance the entity facing because it gets ignored and its always facing right. It you use changeentityproperty, it won't work.

**Comment by DCurrent** [comment]
Please be more specific. Is the entity direction not changing or is the clipping?

The clipping effect isn't supposed to change direction because it doesn't have a direction. It's just a vector based effect applied as the entity is displayed. You have to do the math work yourself for left and right.

**Comment by dbaldan** [comment]
The entity. It always shows facing right. If you apply a negative x velocity, it will move left, but the graphic is still facing right. But I think its related to what you had explained at CC:

> As per universal coding practices, graphic effects are based on screens, not entities. There's no direction flipping. They just do exactly what you tell them, no more or less.

About the other issue, do you think its possible to fix?

**Comment by whitedragon0000** [comment]
this is not an issue. shadow is not a sprite for your drawmethod.
if you want a clipped shadow, you need to script a custom shadow with drawmethod.

**Comment by dbaldan** [comment]
@whitedragon0000 ok about the shadow. But and about the mirror effect?

**Comment by DCurrent** [comment]
@dbaldan Mirror effect works the exact same way as shadow, and consequently shares the same behaviors. To clip, or perform other complex drawing methods, you have to script your own mirror effect. It's actually a lot easier than it sounds. Same principal as drawing shadow trails.

**Comment by dbaldan** [comment]
@DCurrent I see. Thanks for the explanation.
