### ISSUE TITLE
Translation for Korean (Attached txt file)

### ISSUE THREAD

**Issue by DDinghoya** [DCurrent/openbor#269]
**Is your feature request related to a problem? Please describe.**
I would like to help with Korean translation.

**Describe the solution you'd like**
Please use the attached translated text.

**Describe alternatives you've considered**
Korean font information is also required.

**Additional context**
N/A

[translation_ko.zip](https://github.com/DCurrent/openbor/files/9388798/translation_ko.zip)

**Comment by DCurrent** [comment]
This is not an engine code issue. Please post things like this into the forum: https://www.chronocrash.com
