### ISSUE TITLE
Linux Arm64 Build

### ISSUE THREAD

**Issue by coreybruce** [DCurrent/openbor#279]
**Is your feature request related to a problem? Please describe.**
Linux Arm64 build, even a appimage would be a good start allowing people to play openbor games on Linux Arm64

**Comment by 2play** [comment]
no interest on this take

**Comment by msmalik681** [comment]
It would be nice to add this especially as you could probably already compile for arm64 but this is not something I will look into until OpenBOR 4.0 drops but that should not be long now.

**Comment by 2play** [comment]
Some news for all my friends and of PlayBox
I have compiled a binary and made setup for OpenBOR 4 compatible with RockPro64 (arm64)
I will release publicly soon with my RockPro64 base
![Screenshot from 2023-12-07 12-17-45](https://github.com/DCurrent/openbor/assets/30235736/fc8cf882-e5cb-4816-9f2d-ec8ca9442285)

**Comment by coreybruce** [comment]
Awesome news! I hope we can get native compiled binaries and not just app images, I've got a AUR package that takes apart the current appimage and I've noticed that it also doesn't have controller support

**Comment by 2play** [comment]
> Awesome news! I hope we can get native compiled binaries and not just app images, I've got a AUR package that takes apart the current appimage and I've noticed that it also doesn't have controller support

I ll check the controller now that you mentioned it. KB was my initial test

**Comment by coreybruce** [comment]
> > Awesome news! I hope we can get native compiled binaries and not just app images, I've got a AUR package that takes apart the current appimage and I've noticed that it also doesn't have controller support
> 
> I ll check the controller now that you mentioned it. KB was my initial test

Sweet thanks for that

**Comment by 2play** [comment]
> > > Awesome news! I hope we can get native compiled binaries and not just app images, I've got a AUR package that takes apart the current appimage and I've noticed that it also doesn't have controller support
> > 
> > 
> > I ll check the controller now that you mentioned it. KB was my initial test
> 
> Sweet thanks for that

Controller works OK!

**Comment by coreybruce** [comment]
Do you have the compiled binaries  to test @2play ?  :smile:

**Comment by msmalik681** [comment]
For now we do not officially support arm and for now there are no plans to so im closing thos down.

**Comment by 2play** [comment]
> Do you have the compiled binaries to test @2play ? 😄

Get my Vanilla+ base.

**Comment by coreybruce** [comment]
> For now we do not officially support arm and for now there are no plans to so im closing thos down.

if it can be compiled on Linux x64 I see now reason why Arm64 couldn't be supported when it is literally no extra work for you and the same process as compiling on Linux x64

**Comment by coreybruce** [comment]
> > Do you have the compiled binaries to test @2play ? 😄
> 
> Get my Vanilla+ base.

Get my Vanilla+ base.? do you have a link to your binary?

**Comment by DCurrent** [comment]
The answer was given and issue closed. This is starting to veer into port begging territory. I am locking the thread and don't want to hear about it again.
