### ISSUE TITLE
Invalid header

### ISSUE THREAD

**Issue by Unitrunker** [DCurrent/openbor#28]
stristr.h contains a one line function prototype under the GPL.

> char* stristr(char* haystack, char* needle);

The implementation - located in stristr.c (a public domain license) does not match the prototype.

> char *stristr(const char *String, const char *Pattern)
> { ...

**Comment by Unitrunker** [comment]
FYI - searching for "GPL" reveals a few hits.
https://github.com/DCurrent/openbor/blob/d8e1fa0f4a508724aa1db19fbc0311f434ad3432/tools/borpak/source/scandir.c
https://github.com/DCurrent/openbor/blob/d8e1fa0f4a508724aa1db19fbc0311f434ad3432/tools/borplay/source/borplay.c
https://github.com/DCurrent/openbor/blob/d8e1fa0f4a508724aa1db19fbc0311f434ad3432/engine/source/gfxlib/scale2x.c
https://github.com/DCurrent/openbor/blob/d8e1fa0f4a508724aa1db19fbc0311f434ad3432/tools/borpak/source/borpak.c

**Comment by whitedragon0000** [comment]
the prototype is char *stristr(const char *String, const char *Pattern); into stristr.h
