### ISSUE TITLE
issues with Openbor 4.0 Build 7533 in wine running marvel-first-alliance-2

### ISSUE THREAD

**Issue by coreybruce** [DCurrent/openbor#289]
Please complete the following template to help us investigate your issue. Developer time is very limited - incomplete issue reports may be ignored and deleted.

**Note:** Legacy builds are not supported. Any fixes will be applied to the latest engine builds.

## Description
Fullscreen option doesn't work in Opengl or SDL mode and character screen shows up blank with no character icons

## Debugging
here is a log of 4.0 when changing to fullscreen mode

```
wine ./OpenBor.exe                       ✔ 
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:win:RegisterTouchWindow hwnd 00020060, flags 0x3 stub!
0024:fixme:wgl:X11DRV_wglChoosePixelFormatARB unused pfAttribFList
0024:fixme:msctf:ThreadMgr_ActivateEx Unimplemented flags 0x4
0024:fixme:imm:ImeSetCompositionString himc 00010052, index 9, comp 006F0036, comp_len 2, read 006F0036, read_len 2 semi-stub!
0024:fixme:imm:ImeSetCompositionString Read string unimplemented
0024:fixme:imm:NotifyIME himc 00010052, action 0x11, index 0, value 0 stub!
0140:fixme:avrt:AvSetMmThreadCharacteristicsW (L"Pro Audio",03D9FEAC): stub
0140:fixme:avrt:AvRevertMmThreadCharacteristics (12345678): stub
0024:fixme:imm:ImeSetCompositionString himc 00010052, index 9, comp 006F0036, comp_len 2, read 006F0036, read_len 2 semi-stub!
0024:fixme:imm:ImeSetCompositionString Read string unimplemented
0024:fixme:imm:NotifyIME himc 00010052, action 0x11, index 0, value 0 stub!
0024:fixme:win:RegisterTouchWindow hwnd 00030060, flags 0x3 stub!
014c:fixme:avrt:AvSetMmThreadCharacteristicsW (L"Pro Audio",055BFEAC): stub
0144:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
0150:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
0024:err:d3d:wined3d_swapchain_resize_buffers Something's still holding back buffer 0 (019FB8F0).
0154:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
014c:fixme:avrt:AvRevertMmThreadCharacteristics (12345678): stub
```
### Reproduce
Start story and go to select a character

Go into the settings and set the game to fullscreen mode

### Expected behavior
Character screen should show the characters in the grid menu and the fullscreen option should work as intended

### Screenshots
![image](https://github.com/DCurrent/openbor/assets/8393780/050ac803-de64-4373-b27a-1d969d1d8a53)

![image](https://github.com/DCurrent/openbor/assets/8393780/981c7fc3-7924-4a26-99cd-6108f3be04c8)

### Version
4.0 Build 7533 and I also tested 3.0 Build 6391 and noticed the same issue tho 3.0 does have a Linux version.

- Platform
Linux with the Windows version with in Wine due to there not being a Linux version of 4.0 and unable to build it.

**Comment by dbaldan** [comment]
That is weird, because I've tried my PDC game and it runs in full screen perfectly in windows in both SDL and OpenGL (btw you can hit ALT+ENTTER to change to fullscreen). Both in V4 and 6391 under windows.

**Comment by coreybruce** [comment]
> That is weird, because I've tried my PDC game and it runs in full screen perfectly in windows in both SDL and OpenGL (btw you can hit ALT+ENTTER to change to fullscreen). Both in V4 and 6391 under windows.

Yeah like I said I am testing 4.0 in wine on Linux because there is no Linux version yet and the compiling fails but 3.0 has a native version and goes fullscreen, I just wanted to report that in wine openbor's fullscreen doesn't work correctly and so it can get fixed. Obviously a native version is better but I still think it should be fixed if possible.

**Comment by msmalik681** [comment]
I will not accept any issues that relate to "wine" only issues with the native Linux port or the native Windows port working on real hardware. Closing this down.

**Comment by coreybruce** [comment]
Oh so you aren't support Linux native binaries and only the Windows version through wine?
