### ISSUE TITLE
Is it possible to update (more or less quickly) to opengl api 4.6?

### ISSUE THREAD

**Issue by whitedragon0000** [DCurrent/openbor#29]
Is it possible to update (more or less quickly) to opengl api 4.6?
I ask to you Plombo because I know that you have taken care of this part of the engine.

**Comment by Plombo** [comment]
That's not actually something we want to do. Newer versions of OpenGL can only be supported by modern GPUs, while older versions of the API are supported by all hardware regardless of age. There's no real advantage for

**Comment by Plombo** [comment]
Sorry, accidentally hit "close and comment" while still typing.

Anyway, there's no real advantage to "upgrading"; it would limit hardware compatibility, and it wouldn't improve performance or anything.
