### ISSUE TITLE
New Debug Setting Option: Ingame Debug Log

### ISSUE THREAD

**Issue by PauloHPBender** [DCurrent/openbor#290]
**Is your feature request related to a problem? Please describe.**
I'm starting a new project from ground, and even though I have some experience working with OpenBoR scripts, I feel the necessity of a ingame log that does not require hand scripted workarounds like a OnDraw function.

**Describe the solution you'd like**
 I believe that a new Debug Setting option called "Debug Log" or "Ingame Log", featuring a list of the 10 or 20 last log entries to shown ingame (preferably on the left top corner?) would suffice and help the life of many developers.

**Describe alternatives you've considered**
I've considered using a streamfile function to store my custom logs and read them through a powershell script, but I believe a proper, ingame, native function is the best toll for most.

**Comment by DCurrent** [comment]
Sorry @PauloHPBender, I can't really justify putting this into code. All you have to do is load the log in your browser instead of the text reader app and use the refresh button. I might consider adding HTML5 tags with an auto refresh option, this would let you see entries as they come.
