### ISSUE TITLE
New Run Config field: run.speed.z

### ISSUE THREAD

**Issue by PauloHPBender** [DCurrent/openbor#294]
**Is your feature request related to a problem? Please describe.**
In OpenBoR 4.0, the new feature `run.speed.x`, along with all the other new configurations, allowed greater freedom for the developer, and yet, I feel that a `run.speed.z` is lacking.

**Describe the solution you'd like**
Being able to declare clearly how fast the character is able to move in the Z axis while running.

**Describe alternatives you've considered**
I've considered zeroing all run config values and creating a custom animation where I could manipulate both X and Z speed, but it seems counterintuitive and a reinventing of the wheel.

**Additional context**
My current project has characters that run very fast, but with little maneuverability (IOW, high X speed, low Z speed), while others run slower bur with more finesse.

**Comment by DCurrent** [comment]
@PauloHPBender,

This feature is already in progress for future releases. Part of the code is already done.
