### ISSUE TITLE
Appimage require fuse libfuse.so.2 but the lib is here... appimage can't be extracted...

### ISSUE THREAD

**Issue by naxil** [DCurrent/openbor#297]
libfuse.so.2 are on my $ /lib/x86_64-linux-gnu/  folder and the libfuse on repository is already installed

## Description of error (copy paste the terminal error)
./OpenBOR-Linux-x86.AppImage 
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information

### Reproduce
Lubuntu 22.04 kernel 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
download the latest appimage, make the file executable (chmod +x) and launch it

### Expected behavior
launch the openbor

###Version
https://github.com/DCurrent/openbor/releases/tag/v7533)

## Additional context
The 3.0 version works perfect...

**Comment by coreybruce** [comment]
Hey this appimage is 32bit so you will need lib32-fuse2, I'll have to test if it works with lib32-fuse3 but I have reported this issue to the developer as I was the first to test it for him :)

**Comment by coreybruce** [comment]
You can now get the 64bit and 32bit version, you may close the issue :)
