### ISSUE TITLE
Debian Packaging for OpenBOR

### ISSUE THREAD

**Issue by coringao** [DCurrent/openbor#3]
Hello,

My intention on OpenBOR is to make it available in Debian/Ubuntu Linux distributions, simply for users beginners.

The source code is well organized to work on the packaging, but I need you to remove the other platforms that have in the compilation leaving only the GNU/Linux version.

Can you make that change the part or can I make that change myself?

Thanks!

**Comment by DCurrent** [comment]
I'm afraid I can't do that - multiple ports are one of the main hallmarks of OpenBOR. This is coming from a guy who HATES ports with a bitter passion. Most of them were done without consent and then the author left with us (me) holding the bag trying to support them. Were it up to me (well technically it is, but I'm just not that mean), I'd drop every single port and take the engine back where it started - PC only.

I have to be honest - not a big fan of branches either. OpenBOR is a unique animal. It's user content driven, and branching just leads to compatibility issues left and right. Still, long as you're following the license I won't try to stop you. I just can't really offer a whole lot of support for it. You can always just remove all the other tool chains on your branch and modify the batch to only compile Linux, then grab engine updates as they come along. The tools and engine are divided up specifically so you can do that sort of thing.

I know that's not really what you wanted to hear, but hope it does help some.

DC

**Comment by coringao** [comment]
A pity that this is happening this way.

> _You can always just remove all the other tool chains on your branch and modify the batch to only compile Linux, then grab engine updates as they come along._

Okay, I made a fork in this source code to leave only GNU/Linux version. After completing I will warn you, and publish in the Debian project.

Thanks!
