### ISSUE TITLE
Compile Build in Log

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#30]
Actually, when we run OpenBOR, we only have compile date without the build version:

> OpenBoR v3.0 Build , Compile Date: Dec 22 2016

In fact, there is a build version, but it's wrong (it shows v3.0 when I am using build 4432). Long time ago, we had the build version showing the right (and more complete) information.

This could be helpful when debuging, because we need to _guess_ the build version by the compile date.

**Comment by jbeich** [comment]
#31 was too optimistic: v4696 and v4699 released after the fix still have empty `VERSION_BUILD`. Given Git tags are now less predictable it'd be nice to embed tag/commit via `git describe --tags --long` as well. Can someone reopen the issue?
