### ISSUE TITLE
Libretro port?

### ISSUE THREAD

**Issue by walterheisenberg** [DCurrent/openbor#32]
Did you ever think about to port OpenBOR into a libretro-core? 
> A libretro core is a program (a game/emulator/miscellaneous) that has been ported to the libretro API so that it can be used by libretro frontends.

https://www.libretro.com/index.php/develop/
With RetroPlayer Kodi18 (Leia)  on the horizon ...
This would be awsome!
Thx

**Comment by DCurrent** [comment]
There are no plans to add more ports at this time. Sorry.
