### ISSUE TITLE
[Suggestions] Mouse + Autofire

### ISSUE THREAD

**Issue by SilentMRG** [DCurrent/openbor#322]
Greetings!

These days I was playing some games on the FinalBurn Neo emulator, and I noticed that it supports mouse and rapid fire. So I was thinking that it would be a good idea to add support for these things in the engine, I mean, add support for the left, right and middle mouse buttons, plus autofire which will be very useful in games with shooting sessions.

Rapid fire basically exists to save you mashing the fire button, repeatedly to the point of ruining the button over time. Playing only on the keyboard is bad, and we don't always have a gamepad at our disposal. Anyway, I believe that these things are not difficult to implement in the engine.

Thank you in advance;
Best regards!

**Comment by DCurrent** [comment]
I'm sorry @SilentMRG, but OpenBOR is not an emulator, and is not meant to behave like one. It is a game engine, and the creator has prerogative over how games built with it play. It is already quite easy for creators to implement auto rapid fire into games if they wish, but the engine will not force that feature on them. You would be better off asking the creator of specific games to add this.

**Comment by SilentMRG** [comment]
Well, I think you missed the point... I know OpenBOR is not an emulator. The quote from the emulator was just to exemplify the features: Mouse and Autofire. Anyway, there are native PC games with mouse support, examples: Bloodstained Curse of the Moon 1 and 2, Huntdown, Tyrian, Raptor - Call of the Shadows (these two even support mouse movement), Guns, Gore and Cannoli 1 and 2 have mouse support, with the second having movement support. Anyway, if you can't support the mouse, that's okay mate.

Regarding autofire, I've read developers say that this is a feature that should be added to the engine, because on they can't implement it alone. That's why I suggested this here.

**Comment by dbaldan** [comment]
> Regarding autofire, I've read developers say that this is a feature that should be added to the engine, because on they can't implement it alone. That's why I suggested this here.
I have to disagree @SilentMRG . Autofire is something kinda easy to implement with few scripts.  There are many examples on the forum of games which have this. Also, its not a "must have" feature.

About the mouse... that could be something which could be thinked about in the future to expand the engine possibilities in terms of which games could be done.

**Comment by SilentMRG** [comment]
> I have to disagree @SilentMRG . Autofire is something kinda easy to implement with few scripts. There are many examples on the forum of games which have this. Also, its not a "must have" feature.

So it's a somewhat arbitrary support. Some developers say that it depends on being added to the engine, and you say that through some scripts the developer can add it. When I suggested autofire, I meant an "enable/disable" option in the engine, just like the option to "enable/disable" Haptic Feedback support, or as it is called in the gamepad's "rumble mode" engine, for example.

> About the mouse... that could be something which could be thinked about in the future to expand the engine possibilities in terms of which games could be done.

And in my opinion, mouse support is as important as the keyboard. Honestly, I don't understand why some developers in general only add keyboard support. It even seems like these guys are trapped in spacetime in a time where there is no mouse. XD
