### ISSUE TITLE
OpenBOR does not recognize correct ps2 adapter

### ISSUE THREAD

**Issue by Chavooj** [DCurrent/openbor#33]
Sorry for my english.

A ps2 adapter not work correct in recent versions of engine. Button configuration is confusing in this gamepad. In older versions, this problem does not happen, everything works fine. But as of the 2014 versions, the buttons are not recognized correctly.
I would ask you to evaluate this problem and try to fix it, please.

Details: I tested in Windows 10 and XP operating systems.

Below is the image of the adapter:

![psadapter](https://user-images.githubusercontent.com/36929636/36803448-53e6f380-1c96-11e8-9442-8ec33f23d543.jpg)

**Comment by dbaldan** [comment]
It's not the first time I heard a comment about this, but I have the same PS2 convertor and it works. Some of the videos I made about my mod with my son were made using this adaptor.

**Comment by DCurrent** [comment]
I'm sorry friend, but it seems the adaptor does work for others. Even if it didn't work, I don't have this adaptor and am not willing to go buy one just to test. Sorry. 

Closing ticket.
