### ISSUE TITLE
OpenGL Alignment

### ISSUE THREAD

**Issue by DCurrent** [DCurrent/openbor#35]
@Plombo I noticed that the default OpenGL has a pretty nasty issue with grid alignment. In 480 widescreen (presumably others, but only tested 480*272) mode, the top Y position is moved ~25 pixels off screen, cutting off the top of levels and breaking scripted draw functions.

To test this, I wrote a [grid drawing function](https://github.com/DCurrent/openbor-script-avalanche/blob/master/dc_draw_grid.c). Run it in the update of any module to test. See the following screen shots:

## SDL

SDL mode in normal and double size. Notice the grid and scripted enemy status. The 0 line is at top of screen, enemy icons and life all appear as intended.

![ga-sdl-0](https://user-images.githubusercontent.com/5900142/37716792-b8d35bca-2cf5-11e8-8771-645b9e028643.PNG)
![ga-sdl-1](https://user-images.githubusercontent.com/5900142/37716793-b8e7a292-2cf5-11e8-8442-641167fddbd8.PNG)

## OpenGL

In OpenGL, the enemy HUD is drawn off screen, grid does not appear until line 30 and part of the stage is cut off. Also notice how in double size, the cutoff is not so severe. Continuing to increase the size beyond *2 will eventually bring all items back into view. The bottom remains aligned correctly.

![ga-opengl-0](https://user-images.githubusercontent.com/5900142/37717007-33bf9934-2cf6-11e8-9da8-f5961feee14a.PNG)
![ga-opengl-1](https://user-images.githubusercontent.com/5900142/37717008-33ceab0e-2cf6-11e8-93bf-9f534aa52411.PNG)

**Comment by rofl0r** [comment]
looks as if opengl would consider the window decorations (title bar) as part of the drawing area...

**Comment by DCurrent** [comment]
@rofl0r my first thought, but since scale setting affects how much is cut off I'm not so sure.

**Comment by Plombo** [comment]
So I can see the issue in your screenshots, but I can't actually reproduce it in any build I make. I've tried both Linux and Windows, and compiling with both old and new versions of SDL2, but whatever I do, everything always comes out aligned fine in OpenGL mode.

It does look like what rofl0r said, but if the window decorations are really being counted as part of the display area, the issue seems beyond the scope of what we could mess up in OpenBOR. There's always the possibility of some weird bug in SDL, or that your graphics drivers got a bad update recently...

**Comment by DCurrent** [comment]
What Windows version did you test with? I'm on 10 with a 4K screen, maybe it is a graphic driver issue.

**Comment by Plombo** [comment]
Also Windows 10, though my screen is only 1080p.

**Comment by whitedragon0000** [comment]
I updated sdl to 2.0.8 for windows recently. Try it downloading new tools

**Comment by dbaldan** [comment]
I tried with OpenGL and there is no bug for me

**Comment by DCurrent** [comment]
Since no one other than myself can reproduce this issue, I'm closing the ticket.
