### ISSUE TITLE
update to WINDOWS SDL 2.0.8 causing no audio

### ISSUE THREAD

**Issue by whitedragon0000** [DCurrent/openbor#36]
Using precompiled mingw sdl2 2.0.8 from official site the static libSDL2.a causing no audio.
Any help?
I upload the my compiled SDL2_gfx 1.0.4 with SDL2 2.0.8 for any help.
 
[SDL2_gfx.zip](https://github.com/DCurrent/openbor/files/1844442/SDL2_gfx.zip)

**Comment by whitedragon0000** [comment]
latest working SDL2 2.0.5 (tested) from 2.0.6 no audio

**Comment by dbaldan** [comment]
@whitedragon0000 I've tried the 4750 build for windows and the audio works fine.

**Comment by whitedragon0000** [comment]
I reverted sdl2 api to 2.0.5 in windows.
from sdl2 2.0.6 to up (for windows) sdl uses wasapi api that force audio sampling to 32bit.
openbor uses 16/8 bit so before passing audio sample to sdl first need to resampling the audio to 32 bit.
Any help?
I can't do it, I have no time to study openbor audio sampling.
Thanks

**Comment by dbaldan** [comment]
But do we need to update it to 2.0.6? What are the beneficts?

**Comment by whitedragon0000** [comment]
it is important to prepare the code for the future, otherwise you can not run update ...

**Comment by whitedragon0000** [comment]
maybe now it works!!
check it!!

**Comment by whitedragon0000** [comment]
Issue on touch on virtual game pad

**Comment by whitedragon0000** [comment]
Issue on touch on virtual game pad
