### ISSUE TITLE
Crash on Projectile Hit

### ISSUE THREAD

**Issue by DCurrent** [DCurrent/openbor#43]
I noticed while testing modifications to projectile behavior that some projectiles in my test project cause a program error on hit. 

On further inspection it was not the projectile specific changes, and is being caused by an earlier modification. My guess is I've just fat-fingered something during my property project updates, left a dangling pointer laying around, and it slipped through testing until I focused specifically on projectiles. 

Just in case this comes up, I'm aware and working on it.

**Comment by whitedragon0000** [comment]
DC in community found another bug related to mp recovery. I just want to notify it. Probably related at these last updates..

**Comment by DCurrent** [comment]
Same here @whitedragon0000, I'm doing all I can. There's not a thing I can do about the MP recovery until I finish cleaning up the spaghetti logic that runs it. 

Back to issue topic, revision 6273377 is known working. Just need to test forward from there until I find the bad commit.

**Comment by DCurrent** [comment]
Last known good c254a385cce5e9078058289d8644e2b51d251f60.

**Comment by DCurrent** [comment]
Last known good bebea4e692d797d920d353ba81abecbfe597bedc.

**Comment by DCurrent** [comment]
Last known good 018879c0afcef57dcc84611f4e50b25c536c602b.

**Comment by DCurrent** [comment]
First known bad 5d8a9fb602c0801c177ac317b755ce79b088633f.

**Comment by DCurrent** [comment]
First known bad 8498889b963dbdbdc3cd3403e5ead9893bee39b1.

**Comment by DCurrent** [comment]
Last known good 6dfc002ce53f495263993176044c9dbf54f5e33b.

**Comment by DCurrent** [comment]
Last known good 3dcc15590ce52df866861056a0311c4ae851f9f4.

**Comment by DCurrent** [comment]
Last known good 8101066b7fda975b232ba11ea5b2f14c157e731a.
