### ISSUE TITLE
JoyToKey keymapper is unable to map arrow keys in openbor

### ISSUE THREAD

**Issue by tonywoode** [DCurrent/openbor#56]
see http://www.chronocrash.com/forum/index.php?topic=3869.0

https://joytokey.net/en/ - the latest version v5.9 can be used, though the problem is evident back to at least v4.5...

in  openbor v3 build 4107 from 2015, and in all previous versions I tested, joytokey is able to map arrow keys to joypad movement with no problems
in v3 build v4111 (the next version available on github) this is broken, though action buttons can still be mapped to joypad buttons without issue. 

This issue remains up to the latest release of openbor to date. I don't think the joypad used will make a difference. I am using dinput.

**Comment by whitedragon0000** [comment]
after 4107 SDL is updated to 2.0.

**Comment by whitedragon0000** [comment]
keymapper not support however
