### ISSUE TITLE
Would it be possible to launch games individually with Wiiflow?

### ISSUE THREAD

**Issue by John3d** [DCurrent/openbor#58]
Currently, if you try to load a game from Wiiflow, always load the Openbor selection menu to choose the game.

Could not you avoid that menu and load the game directly?

Thanks

**Comment by msmalik681** [comment]
It is possible that is what i am trying to implement into the android port I may look at other ports when I am done.

**Comment by John3d** [comment]
Thanks, I think it would be great if it was implemented in all versions

**Comment by msmalik681** [comment]
It would have to be done when compiling the engine the offical build will still load from a pak list

**Comment by Plombo** [comment]
OpenBOR will launch directly into a game if there's only one pak in the paks folder. If you really want to launch games separately like that, just make separate directories in the apps folder for each game, each with its own copy of the OpenBOR executable. There's no need to change the engine for this.
