### ISSUE TITLE
Huge pack file

### ISSUE THREAD

**Issue by ChillyWillyGuru** [DCurrent/openbor#59]
There a HUGE (1GB) pack file in the .git directory of the repo that makes the repo ridiculous in size named: pack-bad2c1c73c3088c38db4c0294dcb050946913b2b.pack
Is that supposed to be there? And what is it?

**Comment by msmalik681** [comment]
the whole .git directory has nothing to do with the engine itself and you can download the source code directly from GitHub site without including that folder.
