### ISSUE TITLE
Crash On Open - Log Error?

### ISSUE THREAD

**Issue by DCurrent** [DCurrent/openbor#7]
Latest commit crashes on open. Likely due to log enhancements causing a seg fault.

**Comment by guimabros** [comment]
i had the same bug compiling from the source today

**Comment by DCurrent** [comment]
I haven't fixed the bug yet, so that's no surprise. It will be ~2 weeks and I can get back to working on the source again.

**Comment by whitedragon0000** [comment]
Solved
