### ISSUE TITLE
OpenBOR controller issues

### ISSUE THREAD

**Issue by dbaldan** [DCurrent/openbor#70]
NSW had made a video showing how the controllers are acting strange in OpenBOR.
If you watch the video, you can spot some weird things happening

http://www.chronocrash.com/forum/index.php?topic=4005.0

**Comment by DCurrent** [comment]
We have an ongoing discussion about this as of 2028-12-17 in development area of forum. @plombo is looking into it.

**Comment by nsw27** [comment]
can someone please send me a working openbor build to test this has been addressed before closed ? (a version of engine without png error crash?) I would love to have this controller issue resolved asap for my games if it has been addressed. Thank you
