### ISSUE TITLE
Wii Port - Enemies moving horizontally when they fall to the floor

### ISSUE THREAD

**Issue by SieKensou** [DCurrent/openbor#71]
I have tested various .pak files and I noticed this problem. Watched some videos of these packs and the enemies shouldn't move like that when they are on the floor (they should be stopped in the same place). And they just continue moving horizontally on the floor until the end of the stage...
I happens in all the games I have tested until now....

**Comment by dbaldan** [comment]
This were already fixed on the code (I think its on the latest release).

**Comment by msmalik681** [comment]
Yes it was !

**Comment by SieKensou** [comment]
Cool! I tested version 6385 and it works perfect now (I was using 6384). Thanks for the good job!
I'm noticing other problem in the game Night Slashers X. When Maybe it's related or it's something similar. When I perform a special move to the left (left, left, attack or down, left, attack), at the end of the move, the characters is moved suddenly to the right like if he was pushed away. It works fine when you peform these moves to the right... It seems to happen when the moves uses too much distance horizontally...
Again, I watched some videos of the game and it should work fine...
I don't know if it happens in other games, I don't have too much of my .pak files here...

**Comment by dbaldan** [comment]
Yes, it's a know issue. Its related only with the WII port.

**Comment by SieKensou** [comment]
Okay, I hope it can be fixed. It's a great job what you guys are doing with this engine and I love to play it on the Wii.

**Comment by msmalik681** [comment]
I am aware of the velocity bug and i hate it i have been investigating a lot into this bug but have not fully narrowed down the problem script i think its how the wii port handels float values by script.

**Comment by SieKensou** [comment]
Yeah, this bug is very annoying and it would be great that it could be fixed in some way. In the game I said it happens only when doing the moves to the left side. Is it always like this?

P.S.: I have a small question that I still couldn't solve. How should I name the screenshots and where should I put them to appear as a preview when I'm selecting a game? Can I put more than one and all will be showed a slideshow?
