### ISSUE TITLE
Problem Starting OpenBOR

### ISSUE THREAD

**Issue by KoldMonster12** [DCurrent/openbor#75]
Hey, I tried starting OpenBOR for Windows and it refused to start.  Will someone try to figure out the problem was?  Thank you.

![openbor-issue02](https://user-images.githubusercontent.com/42454517/44241422-d7f09c00-a191-11e8-8152-c81c8931797e.png)
![openbor-issue01](https://user-images.githubusercontent.com/42454517/44241423-d7f09c00-a191-11e8-95b9-afcfdcd264bb.png)

**Comment by msmalik681** [comment]
Are you using the latest build 6390 : https://github.com/DCurrent/openbor/releases/tag/6390

**Comment by KoldMonster12** [comment]
Yes.

**Comment by msmalik681** [comment]
multiple users have reported no fault using the windows port this issue maybe connected to some other fault with your specific system.
