### ISSUE TITLE
Wii port - FX sounds plays too low

### ISSUE THREAD

**Issue by SieKensou** [DCurrent/openbor#76]
I'm not sure why but I always have to put the volume of the FX at maximum and even with that they doesn't play too high... I think something is broken there.

These changes doesn't work for the OpenBOR menus? Is not suposed that the "click" that sounds when I'm changing the value of the FX should sound high or low depending of the value? Because I don't see difference when changing the value to a high volume...

**Comment by msmalik681** [comment]
Still trying to fix the previews then I will look in to this.

**Comment by SieKensou** [comment]
Thanks @msmalik681

**Comment by msmalik681** [comment]
this is my current focus but I am useless with audio stuff I have been looking over the code for days without any progress I will ask Plombo for help on this.

**Comment by SieKensou** [comment]
I hope you can do something. It seems that from the default value to down, it downs the volume, but from the default value to up, it doesn't high the volume... I could be wrong, but this is what I noticed yesterday with one game.

**Comment by msmalik681** [comment]
@SieKensou I have tested and I can see what you mean when you increase BMG volume from the menu there is a noticeable difference but with SFX it is a very small increase.  This is something I would have to ask @Plombo to look into I am not very good with audio coding.

**Comment by DCurrent** [comment]
@msmalik681 did you ever hear from @Plombo?

**Comment by msmalik681** [comment]
Nope

**Comment by DCurrent** [comment]
Closing. There's no one around to support the Wii port and I may just drop it period. There have been several audio updates since this issue. We can revisit if it comes back up,
