### ISSUE TITLE
Make the main window larger

### ISSUE THREAD

**Issue by a7mag3ddon** [DCurrent/openbor#80]
Hello,

Please can you add an option (or the ability to use mouse to grab and stretch) to make the main window larger, on my screen its tiny and can barely read the text.

**Comment by DCurrent** [comment]
OpenBOR already supports window size. Go to video options and you can choose the size you need. Due to portability, support of drag sizing is a very low priority.

**Comment by msmalik681** [comment]
You can set full screen by setting it in options or press ctrl + return.

**Comment by a7mag3ddon** [comment]
Presssing ctrl+enter key just starts the highlighted game, using a PC is there a different way to get to settings?

**Comment by msmalik681** [comment]
Press ctrl+enter once openbor is in full screen next time you start it the programme should be in full screen from the start.

**Comment by a7mag3ddon** [comment]
That doesnt work for me, pressing ctrl+enter just starts the game thats highlighted.

**Comment by msmalik681** [comment]
Press it before you get to the pak selection menu

**Comment by a7mag3ddon** [comment]
still the same, does nothing.

**Comment by a7mag3ddon** [comment]
I got it! its not left CTRL its left ALT+ENTER then it goes full screen :smiley:

**Comment by msmalik681** [comment]
for questions like this I would recommend using the offical openbor forum [](http://www.chronocrash.com/forum/)

**Comment by a7mag3ddon** [comment]
@DCurrent It was a request for emulator main window before you start a game, not when when your in a game as i know you can change game window settings there).

**Comment by DCurrent** [comment]
@a7mag3ddon my bad, sorry about that.
