### ISSUE TITLE
[Wii] Engine crashes on launch when loaded from USB with no SD card inserted

### ISSUE THREAD

**Issue by Plombo** [DCurrent/openbor#85]
It's in the title: OpenBOR on Wii can be loaded fine from a USB device if an SD card is inserted, but if no SD card is in the console, it crashes with a code dump on launch.

**Comment by msmalik681** [comment]
I have tested in every combination on latest build 6412 and it worked just fine !

Can you test wiiflow and see if it can load iso's from usb ?

**Comment by SieKensou** [comment]
I never had a SD inserted on the Wii when playing OpenBOR and I never noticed that problem, it loads fine.

**Comment by Plombo** [comment]
Okay, I've tested further and found the actual problem: the Gamecube controller adapter I have plugged in to the other USB port. Which causes a crash on startup only when launching from USB with no SD card inserted.

Launch from SD, GC controller adapter in USB port 2: no problem
Launch from USB, GC controller adapter in USB port 2, SD card inserted: no problem
Launch from USB, GC controller adapter in USB port 2, no SD card inserted: instant crash

**Comment by Plombo** [comment]
Unsurprisingly given the type of problem, it seems to be a libfat issue.

**Comment by msmalik681** [comment]
So usb works but in a very specific senario device conflict will cause a crash.

Do we have to leave this issue open as we have no control over libfat ?

**Comment by Plombo** [comment]
Feel free to unassign yourself from it, but I want to keep looking into this one. Every other Wii homebrew app works fine with this setup, so it is probably a problem with how we are using libfat.

**Comment by Wiimpathy** [comment]
It will also crash with other devices in port 1 like an usb keyboard for example. Adding a delay to be sure the drive is mounted should fix it. Here's how it's done in genesis plus gx:
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/gx/main.c#L362

Not directly related but https://github.com/DCurrent/openbor/issues/58 has been closed and there's no solution right now. If you're interested, I've made a branch with argument's support and other small fixes here: https://github.com/Wiimpathy/openbor/commits/wii-plugin-and-fixes

In case you don't know what's this plugin system: https://sites.google.com/site/wiiflowiki4/plugins-setup

**Comment by Plombo** [comment]
Thank you, that is incredibly helpful!

**Comment by Plombo** [comment]
Oh, I didn't even notice you'd fixed it in your branch...

**Comment by dbaldan** [comment]
@Wiimpathy thanks for helping :)

**Comment by msmalik681** [comment]
So is this issue fixed now ?

**Comment by DCurrent** [comment]
@msmalik681 I believe so, but can't confirm.

**Comment by Plombo** [comment]
This has been fixed for a while. Forgot to close it.

**Comment by DCurrent** [comment]
Thanks @plombo, I don't have a Wii to confirm.
