### ISSUE TITLE
Bug direct Game Over

### ISSUE THREAD

**Issue by dantedevilMKTC** [DCurrent/openbor#98]
When I play a game and lose my lives, the Game Over screen comes out directly and it does not let me continue, even though I have more credits left.
No matter in any mode, "noshare" will cause all modes to lose all life , go to the Game Over. There are still many "credits".
After some testing on this bug, i found out what actually specificaly is happening and it may help you to fix this.
Normally when loosing all lives the engine was giving the player about 10sec or something to press continue. Now after my testing it seems like you can still continue but only if you press continue very fast after loosing all lives.
So it's not like you can't continue anymore, but what actually happening is that the engine does not giving you the 10sec time to think about it anymore. So, if you are not fast = Game Over.

After testing the builds one by one, I can confirm that the bug started with OpenBOR v3.0 Build 4682.

**Comment by DCurrent** [comment]
Thanks @dantedevilMKTC, I will look into this soon.
