### ISSUE TITLE
Hit Flash

### ISSUE THREAD

**Issue by msmalik681** [DCurrent/openbor#99]
when using the new method "attack.effect.hit.flash.model" to set a hitflash it will overwrite the default flash set in entity header but using old method "hitflash" is still ok.

**Comment by msmalik681** [comment]
when using the new method "attack.effect.hit.flash.model" to set a hitflash it will overwrite the default flash set in entity header but using old method "hitflash" is still ok.

**Comment by nsw27** [comment]
Hi I think this is not related to just the new method as I do not use that and can confirm this issue still remians. 

I reported it a while ago

http://www.chronocrash.com/forum/index.php?topic=4079.0
